# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('signoz')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def access_token(self) -> Optional[str]:
        """
        Access token of the SigNoz API. You can retrieve it from SigNoz UI
        with Admin Role ([documentation](https://signoz.io/newsroom/launch-week-1-day-5/#using-access-token)).
        Also, you can set it using environment variable SIGNOZ_ACCESS_TOKEN.
        """
        return __config__.get('accessToken')

    @_builtins.property
    def endpoint(self) -> Optional[str]:
        """
        Endpoint of the SigNoz. It is the root URL of the SigNoz UI.
        Also, you can set it using environment variable SIGNOZ_ENDPOINT. If not set, it defaults to http://localhost:3301.
        """
        return __config__.get('endpoint')

    @_builtins.property
    def http_max_retry(self) -> Optional[int]:
        """
        Specifies the max retry limit for the HTTP requests made to SigNoz.
        Also, you can set it using environment variable SIGNOZ_HTTP_MAX_RETRY. If not set, it defaults to 10.
        """
        return __config__.get_int('httpMaxRetry')

    @_builtins.property
    def http_timeout(self) -> Optional[int]:
        """
        Specifies the timeout limit in seconds for the HTTP requests made to SigNoz.
        Also, you can set it using environment variable SIGNOZ_HTTP_TIMEOUT. If not set, it defaults to 35.
        """
        return __config__.get_int('httpTimeout')

