# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .alert import *
from .dashboard import *
from .get_alert import *
from .get_dashboard import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_signoz_jooon.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_signoz_jooon.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "signoz",
  "mod": "index/alert",
  "fqn": "pulumi_signoz_jooon",
  "classes": {
   "signoz:index/alert:Alert": "Alert"
  }
 },
 {
  "pkg": "signoz",
  "mod": "index/dashboard",
  "fqn": "pulumi_signoz_jooon",
  "classes": {
   "signoz:index/dashboard:Dashboard": "Dashboard"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "signoz",
  "token": "pulumi:providers:signoz",
  "fqn": "pulumi_signoz_jooon",
  "class": "Provider"
 }
]
"""
)
