# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'AlertNotificationSettingsArgs',
    'AlertNotificationSettingsArgsDict',
    'AlertNotificationSettingsRenotifyArgs',
    'AlertNotificationSettingsRenotifyArgsDict',
]

class AlertNotificationSettingsArgsDict(TypedDict):
    group_bies: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    """
    Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
    """
    renotify: NotRequired[pulumi.Input[Optional['AlertNotificationSettingsRenotifyArgsDict']]]
    """
    The alert re-notification settings.
    """
    use_policy: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    """
    Use policy in the alert. By default, it is false.
    """

@pulumi.input_type
class AlertNotificationSettingsArgs:
    def __init__(__self__, *,
                 group_bies: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 renotify: pulumi.Input[Optional['AlertNotificationSettingsRenotifyArgs']] = None,
                 use_policy: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] group_bies: Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
        :param pulumi.Input['AlertNotificationSettingsRenotifyArgs'] renotify: The alert re-notification settings.
        :param pulumi.Input[_builtins.bool] use_policy: Use policy in the alert. By default, it is false.
        """
        if group_bies is not None:
            pulumi.set(__self__, "group_bies", group_bies)
        if renotify is not None:
            pulumi.set(__self__, "renotify", renotify)
        if use_policy is not None:
            pulumi.set(__self__, "use_policy", use_policy)

    @_builtins.property
    @pulumi.getter(name="groupBies")
    def group_bies(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
        """
        return pulumi.get(self, "group_bies")

    @group_bies.setter
    def group_bies(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "group_bies", value)

    @_builtins.property
    @pulumi.getter
    def renotify(self) -> pulumi.Input[Optional['AlertNotificationSettingsRenotifyArgs']]:
        """
        The alert re-notification settings.
        """
        return pulumi.get(self, "renotify")

    @renotify.setter
    def renotify(self, value: pulumi.Input[Optional['AlertNotificationSettingsRenotifyArgs']]):
        pulumi.set(self, "renotify", value)

    @_builtins.property
    @pulumi.getter(name="usePolicy")
    def use_policy(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Use policy in the alert. By default, it is false.
        """
        return pulumi.get(self, "use_policy")

    @use_policy.setter
    def use_policy(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "use_policy", value)


class AlertNotificationSettingsRenotifyArgsDict(TypedDict):
    alert_states: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
    """
    For which AlertStates of the alert want to get renotified.
    """
    interval: pulumi.Input[_builtins.str]
    """
    Re-notify interval of the alert.
    """
    enabled: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    """
    To enable the re-notification of the alert.
    """

@pulumi.input_type
class AlertNotificationSettingsRenotifyArgs:
    def __init__(__self__, *,
                 alert_states: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 interval: pulumi.Input[_builtins.str],
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] alert_states: For which AlertStates of the alert want to get renotified.
        :param pulumi.Input[_builtins.str] interval: Re-notify interval of the alert.
        :param pulumi.Input[_builtins.bool] enabled: To enable the re-notification of the alert.
        """
        pulumi.set(__self__, "alert_states", alert_states)
        pulumi.set(__self__, "interval", interval)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter(name="alertStates")
    def alert_states(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        For which AlertStates of the alert want to get renotified.
        """
        return pulumi.get(self, "alert_states")

    @alert_states.setter
    def alert_states(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "alert_states", value)

    @_builtins.property
    @pulumi.getter
    def interval(self) -> pulumi.Input[_builtins.str]:
        """
        Re-notify interval of the alert.
        """
        return pulumi.get(self, "interval")

    @interval.setter
    def interval(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "interval", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        To enable the re-notification of the alert.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)


