# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AlertArgs', 'Alert']

@pulumi.input_type
class AlertArgs:
    def __init__(__self__, *,
                 alert: pulumi.Input[_builtins.str],
                 alert_type: pulumi.Input[_builtins.str],
                 condition: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 eval_window: pulumi.Input[Optional[_builtins.str]] = None,
                 evaluation: pulumi.Input[Optional[_builtins.str]] = None,
                 frequency: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 notification_settings: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 schema_version: pulumi.Input[Optional[_builtins.str]] = None,
                 severity: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Alert resource.

        :param pulumi.Input[_builtins.str] alert: Alert name.
        :param pulumi.Input[_builtins.str] alert_type: One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        :param pulumi.Input[_builtins.str] condition: Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        :param pulumi.Input[_builtins.str] description: Human-readable description.
        :param pulumi.Input[_builtins.bool] disabled: Whether the rule is disabled. Defaults to false.
        :param pulumi.Input[_builtins.str] eval_window: Evaluation window (e.g. `5m0s`).
        :param pulumi.Input[_builtins.str] evaluation: Evaluation block as JSON (v2alpha1+). Compared semantically.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency (e.g. `1m0s`).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Custom labels attached to the alert.
        :param pulumi.Input[_builtins.str] notification_settings: Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_channels: Notification channel names the alert routes to.
        :param pulumi.Input[_builtins.str] rule_type: Rule engine type: `threshold_rule` (default) or `promql_rule`.
        :param pulumi.Input[_builtins.str] schema_version: Alert schema version. Defaults to `v2alpha1`.
        :param pulumi.Input[_builtins.str] severity: Severity label (e.g. `info`, `warning`, `critical`).
        :param pulumi.Input[_builtins.str] source: Source URL recorded on the rule.
        :param pulumi.Input[_builtins.str] version: Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        pulumi.set(__self__, "alert", alert)
        pulumi.set(__self__, "alert_type", alert_type)
        pulumi.set(__self__, "condition", condition)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if eval_window is not None:
            pulumi.set(__self__, "eval_window", eval_window)
        if evaluation is not None:
            pulumi.set(__self__, "evaluation", evaluation)
        if frequency is not None:
            pulumi.set(__self__, "frequency", frequency)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if notification_settings is not None:
            pulumi.set(__self__, "notification_settings", notification_settings)
        if preferred_channels is not None:
            pulumi.set(__self__, "preferred_channels", preferred_channels)
        if rule_type is not None:
            pulumi.set(__self__, "rule_type", rule_type)
        if schema_version is not None:
            pulumi.set(__self__, "schema_version", schema_version)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def alert(self) -> pulumi.Input[_builtins.str]:
        """
        Alert name.
        """
        return pulumi.get(self, "alert")

    @alert.setter
    def alert(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "alert", value)

    @_builtins.property
    @pulumi.getter(name="alertType")
    def alert_type(self) -> pulumi.Input[_builtins.str]:
        """
        One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        """
        return pulumi.get(self, "alert_type")

    @alert_type.setter
    def alert_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "alert_type", value)

    @_builtins.property
    @pulumi.getter
    def condition(self) -> pulumi.Input[_builtins.str]:
        """
        Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        """
        return pulumi.get(self, "condition")

    @condition.setter
    def condition(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "condition", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the rule is disabled. Defaults to false.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="evalWindow")
    def eval_window(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Evaluation window (e.g. `5m0s`).
        """
        return pulumi.get(self, "eval_window")

    @eval_window.setter
    def eval_window(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "eval_window", value)

    @_builtins.property
    @pulumi.getter
    def evaluation(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Evaluation block as JSON (v2alpha1+). Compared semantically.
        """
        return pulumi.get(self, "evaluation")

    @evaluation.setter
    def evaluation(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "evaluation", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Evaluation frequency (e.g. `1m0s`).
        """
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Custom labels attached to the alert.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="notificationSettings")
    def notification_settings(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        """
        return pulumi.get(self, "notification_settings")

    @notification_settings.setter
    def notification_settings(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "notification_settings", value)

    @_builtins.property
    @pulumi.getter(name="preferredChannels")
    def preferred_channels(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Notification channel names the alert routes to.
        """
        return pulumi.get(self, "preferred_channels")

    @preferred_channels.setter
    def preferred_channels(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "preferred_channels", value)

    @_builtins.property
    @pulumi.getter(name="ruleType")
    def rule_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Rule engine type: `threshold_rule` (default) or `promql_rule`.
        """
        return pulumi.get(self, "rule_type")

    @rule_type.setter
    def rule_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "rule_type", value)

    @_builtins.property
    @pulumi.getter(name="schemaVersion")
    def schema_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Alert schema version. Defaults to `v2alpha1`.
        """
        return pulumi.get(self, "schema_version")

    @schema_version.setter
    def schema_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schema_version", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Severity label (e.g. `info`, `warning`, `critical`).
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Source URL recorded on the rule.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.input_type
class _AlertState:
    def __init__(__self__, *,
                 alert: pulumi.Input[Optional[_builtins.str]] = None,
                 alert_type: pulumi.Input[Optional[_builtins.str]] = None,
                 condition: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 eval_window: pulumi.Input[Optional[_builtins.str]] = None,
                 evaluation: pulumi.Input[Optional[_builtins.str]] = None,
                 frequency: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 notification_settings: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 schema_version: pulumi.Input[Optional[_builtins.str]] = None,
                 severity: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Alert resources.

        :param pulumi.Input[_builtins.str] alert: Alert name.
        :param pulumi.Input[_builtins.str] alert_type: One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        :param pulumi.Input[_builtins.str] condition: Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        :param pulumi.Input[_builtins.str] description: Human-readable description.
        :param pulumi.Input[_builtins.bool] disabled: Whether the rule is disabled. Defaults to false.
        :param pulumi.Input[_builtins.str] eval_window: Evaluation window (e.g. `5m0s`).
        :param pulumi.Input[_builtins.str] evaluation: Evaluation block as JSON (v2alpha1+). Compared semantically.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency (e.g. `1m0s`).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Custom labels attached to the alert.
        :param pulumi.Input[_builtins.str] notification_settings: Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_channels: Notification channel names the alert routes to.
        :param pulumi.Input[_builtins.str] rule_type: Rule engine type: `threshold_rule` (default) or `promql_rule`.
        :param pulumi.Input[_builtins.str] schema_version: Alert schema version. Defaults to `v2alpha1`.
        :param pulumi.Input[_builtins.str] severity: Severity label (e.g. `info`, `warning`, `critical`).
        :param pulumi.Input[_builtins.str] source: Source URL recorded on the rule.
        :param pulumi.Input[_builtins.str] version: Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        if alert is not None:
            pulumi.set(__self__, "alert", alert)
        if alert_type is not None:
            pulumi.set(__self__, "alert_type", alert_type)
        if condition is not None:
            pulumi.set(__self__, "condition", condition)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if eval_window is not None:
            pulumi.set(__self__, "eval_window", eval_window)
        if evaluation is not None:
            pulumi.set(__self__, "evaluation", evaluation)
        if frequency is not None:
            pulumi.set(__self__, "frequency", frequency)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if notification_settings is not None:
            pulumi.set(__self__, "notification_settings", notification_settings)
        if preferred_channels is not None:
            pulumi.set(__self__, "preferred_channels", preferred_channels)
        if rule_type is not None:
            pulumi.set(__self__, "rule_type", rule_type)
        if schema_version is not None:
            pulumi.set(__self__, "schema_version", schema_version)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def alert(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Alert name.
        """
        return pulumi.get(self, "alert")

    @alert.setter
    def alert(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "alert", value)

    @_builtins.property
    @pulumi.getter(name="alertType")
    def alert_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        """
        return pulumi.get(self, "alert_type")

    @alert_type.setter
    def alert_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "alert_type", value)

    @_builtins.property
    @pulumi.getter
    def condition(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        """
        return pulumi.get(self, "condition")

    @condition.setter
    def condition(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "condition", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the rule is disabled. Defaults to false.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="evalWindow")
    def eval_window(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Evaluation window (e.g. `5m0s`).
        """
        return pulumi.get(self, "eval_window")

    @eval_window.setter
    def eval_window(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "eval_window", value)

    @_builtins.property
    @pulumi.getter
    def evaluation(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Evaluation block as JSON (v2alpha1+). Compared semantically.
        """
        return pulumi.get(self, "evaluation")

    @evaluation.setter
    def evaluation(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "evaluation", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Evaluation frequency (e.g. `1m0s`).
        """
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Custom labels attached to the alert.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="notificationSettings")
    def notification_settings(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        """
        return pulumi.get(self, "notification_settings")

    @notification_settings.setter
    def notification_settings(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "notification_settings", value)

    @_builtins.property
    @pulumi.getter(name="preferredChannels")
    def preferred_channels(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Notification channel names the alert routes to.
        """
        return pulumi.get(self, "preferred_channels")

    @preferred_channels.setter
    def preferred_channels(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "preferred_channels", value)

    @_builtins.property
    @pulumi.getter(name="ruleType")
    def rule_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Rule engine type: `threshold_rule` (default) or `promql_rule`.
        """
        return pulumi.get(self, "rule_type")

    @rule_type.setter
    def rule_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "rule_type", value)

    @_builtins.property
    @pulumi.getter(name="schemaVersion")
    def schema_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Alert schema version. Defaults to `v2alpha1`.
        """
        return pulumi.get(self, "schema_version")

    @schema_version.setter
    def schema_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schema_version", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Severity label (e.g. `info`, `warning`, `critical`).
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Source URL recorded on the rule.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("signoz:index/alert:Alert")
class Alert(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alert: pulumi.Input[Optional[_builtins.str]] = None,
                 alert_type: pulumi.Input[Optional[_builtins.str]] = None,
                 condition: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 eval_window: pulumi.Input[Optional[_builtins.str]] = None,
                 evaluation: pulumi.Input[Optional[_builtins.str]] = None,
                 frequency: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 notification_settings: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 schema_version: pulumi.Input[Optional[_builtins.str]] = None,
                 severity: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A SigNoz alert rule. Top-level fields are typed; the query `condition`, `evaluation`, and `notification_settings` are JSON blobs (export from the SigNoz UI to adapt). Defaults target the v5 / v2alpha1 schema required by SigNoz >= 0.125.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_signoz_jooon as signoz

        # A logs-based alert on the v5 / v2alpha1 schema (SigNoz >= 0.125).
        # The threshold references a notification channel by name.
        high_error_logs = signoz.Alert("high_error_logs",
            alert="High error log volume",
            alert_type="LOGS_BASED_ALERT",
            severity="warning",
            condition=json.dumps({
                "compositeQuery": {
                    "queryType": "builder",
                    "panelType": "graph",
                    "queries": [{
                        "type": "builder_query",
                        "spec": {
                            "name": "A",
                            "signal": "logs",
                            "stepInterval": 0,
                            "aggregations": [{
                                "expression": "count()",
                            }],
                            "filter": {
                                "expression": "severity_text = 'ERROR'",
                            },
                            "having": {
                                "expression": "",
                            },
                        },
                    }],
                },
                "selectedQueryName": "A",
                "thresholds": {
                    "kind": "basic",
                    "spec": [{
                        "name": "warning",
                        "target": 100,
                        "matchType": "1",
                        "op": "1",
                        "channels": [slack["name"]],
                    }],
                },
            }),
            evaluation=json.dumps({
                "kind": "rolling",
                "spec": {
                    "evalWindow": "5m0s",
                    "frequency": "1m0s",
                },
            }),
            preferred_channels=[slack["name"]])
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] alert: Alert name.
        :param pulumi.Input[_builtins.str] alert_type: One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        :param pulumi.Input[_builtins.str] condition: Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        :param pulumi.Input[_builtins.str] description: Human-readable description.
        :param pulumi.Input[_builtins.bool] disabled: Whether the rule is disabled. Defaults to false.
        :param pulumi.Input[_builtins.str] eval_window: Evaluation window (e.g. `5m0s`).
        :param pulumi.Input[_builtins.str] evaluation: Evaluation block as JSON (v2alpha1+). Compared semantically.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency (e.g. `1m0s`).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Custom labels attached to the alert.
        :param pulumi.Input[_builtins.str] notification_settings: Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_channels: Notification channel names the alert routes to.
        :param pulumi.Input[_builtins.str] rule_type: Rule engine type: `threshold_rule` (default) or `promql_rule`.
        :param pulumi.Input[_builtins.str] schema_version: Alert schema version. Defaults to `v2alpha1`.
        :param pulumi.Input[_builtins.str] severity: Severity label (e.g. `info`, `warning`, `critical`).
        :param pulumi.Input[_builtins.str] source: Source URL recorded on the rule.
        :param pulumi.Input[_builtins.str] version: Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AlertArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A SigNoz alert rule. Top-level fields are typed; the query `condition`, `evaluation`, and `notification_settings` are JSON blobs (export from the SigNoz UI to adapt). Defaults target the v5 / v2alpha1 schema required by SigNoz >= 0.125.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_signoz_jooon as signoz

        # A logs-based alert on the v5 / v2alpha1 schema (SigNoz >= 0.125).
        # The threshold references a notification channel by name.
        high_error_logs = signoz.Alert("high_error_logs",
            alert="High error log volume",
            alert_type="LOGS_BASED_ALERT",
            severity="warning",
            condition=json.dumps({
                "compositeQuery": {
                    "queryType": "builder",
                    "panelType": "graph",
                    "queries": [{
                        "type": "builder_query",
                        "spec": {
                            "name": "A",
                            "signal": "logs",
                            "stepInterval": 0,
                            "aggregations": [{
                                "expression": "count()",
                            }],
                            "filter": {
                                "expression": "severity_text = 'ERROR'",
                            },
                            "having": {
                                "expression": "",
                            },
                        },
                    }],
                },
                "selectedQueryName": "A",
                "thresholds": {
                    "kind": "basic",
                    "spec": [{
                        "name": "warning",
                        "target": 100,
                        "matchType": "1",
                        "op": "1",
                        "channels": [slack["name"]],
                    }],
                },
            }),
            evaluation=json.dumps({
                "kind": "rolling",
                "spec": {
                    "evalWindow": "5m0s",
                    "frequency": "1m0s",
                },
            }),
            preferred_channels=[slack["name"]])
        ```


        :param str resource_name: The name of the resource.
        :param AlertArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AlertArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alert: pulumi.Input[Optional[_builtins.str]] = None,
                 alert_type: pulumi.Input[Optional[_builtins.str]] = None,
                 condition: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 eval_window: pulumi.Input[Optional[_builtins.str]] = None,
                 evaluation: pulumi.Input[Optional[_builtins.str]] = None,
                 frequency: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 notification_settings: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 schema_version: pulumi.Input[Optional[_builtins.str]] = None,
                 severity: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AlertArgs.__new__(AlertArgs)

            if alert is None and not opts.urn:
                raise TypeError("Missing required property 'alert'")
            __props__.__dict__["alert"] = alert
            if alert_type is None and not opts.urn:
                raise TypeError("Missing required property 'alert_type'")
            __props__.__dict__["alert_type"] = alert_type
            if condition is None and not opts.urn:
                raise TypeError("Missing required property 'condition'")
            __props__.__dict__["condition"] = condition
            __props__.__dict__["description"] = description
            __props__.__dict__["disabled"] = disabled
            __props__.__dict__["eval_window"] = eval_window
            __props__.__dict__["evaluation"] = evaluation
            __props__.__dict__["frequency"] = frequency
            __props__.__dict__["labels"] = labels
            __props__.__dict__["notification_settings"] = notification_settings
            __props__.__dict__["preferred_channels"] = preferred_channels
            __props__.__dict__["rule_type"] = rule_type
            __props__.__dict__["schema_version"] = schema_version
            __props__.__dict__["severity"] = severity
            __props__.__dict__["source"] = source
            __props__.__dict__["version"] = version
        super(Alert, __self__).__init__(
            'signoz:index/alert:Alert',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            alert: pulumi.Input[Optional[_builtins.str]] = None,
            alert_type: pulumi.Input[Optional[_builtins.str]] = None,
            condition: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            disabled: pulumi.Input[Optional[_builtins.bool]] = None,
            eval_window: pulumi.Input[Optional[_builtins.str]] = None,
            evaluation: pulumi.Input[Optional[_builtins.str]] = None,
            frequency: pulumi.Input[Optional[_builtins.str]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            notification_settings: pulumi.Input[Optional[_builtins.str]] = None,
            preferred_channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            rule_type: pulumi.Input[Optional[_builtins.str]] = None,
            schema_version: pulumi.Input[Optional[_builtins.str]] = None,
            severity: pulumi.Input[Optional[_builtins.str]] = None,
            source: pulumi.Input[Optional[_builtins.str]] = None,
            version: pulumi.Input[Optional[_builtins.str]] = None) -> 'Alert':
        """
        Get an existing Alert resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] alert: Alert name.
        :param pulumi.Input[_builtins.str] alert_type: One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        :param pulumi.Input[_builtins.str] condition: Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        :param pulumi.Input[_builtins.str] description: Human-readable description.
        :param pulumi.Input[_builtins.bool] disabled: Whether the rule is disabled. Defaults to false.
        :param pulumi.Input[_builtins.str] eval_window: Evaluation window (e.g. `5m0s`).
        :param pulumi.Input[_builtins.str] evaluation: Evaluation block as JSON (v2alpha1+). Compared semantically.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency (e.g. `1m0s`).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Custom labels attached to the alert.
        :param pulumi.Input[_builtins.str] notification_settings: Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_channels: Notification channel names the alert routes to.
        :param pulumi.Input[_builtins.str] rule_type: Rule engine type: `threshold_rule` (default) or `promql_rule`.
        :param pulumi.Input[_builtins.str] schema_version: Alert schema version. Defaults to `v2alpha1`.
        :param pulumi.Input[_builtins.str] severity: Severity label (e.g. `info`, `warning`, `critical`).
        :param pulumi.Input[_builtins.str] source: Source URL recorded on the rule.
        :param pulumi.Input[_builtins.str] version: Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AlertState.__new__(_AlertState)

        __props__.__dict__["alert"] = alert
        __props__.__dict__["alert_type"] = alert_type
        __props__.__dict__["condition"] = condition
        __props__.__dict__["description"] = description
        __props__.__dict__["disabled"] = disabled
        __props__.__dict__["eval_window"] = eval_window
        __props__.__dict__["evaluation"] = evaluation
        __props__.__dict__["frequency"] = frequency
        __props__.__dict__["labels"] = labels
        __props__.__dict__["notification_settings"] = notification_settings
        __props__.__dict__["preferred_channels"] = preferred_channels
        __props__.__dict__["rule_type"] = rule_type
        __props__.__dict__["schema_version"] = schema_version
        __props__.__dict__["severity"] = severity
        __props__.__dict__["source"] = source
        __props__.__dict__["version"] = version
        return Alert(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def alert(self) -> pulumi.Output[_builtins.str]:
        """
        Alert name.
        """
        return pulumi.get(self, "alert")

    @_builtins.property
    @pulumi.getter(name="alertType")
    def alert_type(self) -> pulumi.Output[_builtins.str]:
        """
        One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        """
        return pulumi.get(self, "alert_type")

    @_builtins.property
    @pulumi.getter
    def condition(self) -> pulumi.Output[_builtins.str]:
        """
        Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        """
        return pulumi.get(self, "condition")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Human-readable description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the rule is disabled. Defaults to false.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="evalWindow")
    def eval_window(self) -> pulumi.Output[_builtins.str]:
        """
        Evaluation window (e.g. `5m0s`).
        """
        return pulumi.get(self, "eval_window")

    @_builtins.property
    @pulumi.getter
    def evaluation(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Evaluation block as JSON (v2alpha1+). Compared semantically.
        """
        return pulumi.get(self, "evaluation")

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Output[_builtins.str]:
        """
        Evaluation frequency (e.g. `1m0s`).
        """
        return pulumi.get(self, "frequency")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Custom labels attached to the alert.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="notificationSettings")
    def notification_settings(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        """
        return pulumi.get(self, "notification_settings")

    @_builtins.property
    @pulumi.getter(name="preferredChannels")
    def preferred_channels(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Notification channel names the alert routes to.
        """
        return pulumi.get(self, "preferred_channels")

    @_builtins.property
    @pulumi.getter(name="ruleType")
    def rule_type(self) -> pulumi.Output[_builtins.str]:
        """
        Rule engine type: `threshold_rule` (default) or `promql_rule`.
        """
        return pulumi.get(self, "rule_type")

    @_builtins.property
    @pulumi.getter(name="schemaVersion")
    def schema_version(self) -> pulumi.Output[_builtins.str]:
        """
        Alert schema version. Defaults to `v2alpha1`.
        """
        return pulumi.get(self, "schema_version")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Severity label (e.g. `info`, `warning`, `critical`).
        """
        return pulumi.get(self, "severity")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Source URL recorded on the rule.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
        """
        return pulumi.get(self, "version")

