# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['NotificationChannelArgs', 'NotificationChannel']

@pulumi.input_type
class NotificationChannelArgs:
    def __init__(__self__, *,
                 data: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a NotificationChannel resource.

        :param pulumi.Input[_builtins.str] data: Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        :param pulumi.Input[_builtins.str] name: Unique channel name.
        """
        pulumi.set(__self__, "data", data)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Input[_builtins.str]:
        """
        Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        """
        return pulumi.get(self, "data")

    @data.setter
    def data(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "data", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique channel name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _NotificationChannelState:
    def __init__(__self__, *,
                 data: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering NotificationChannel resources.

        :param pulumi.Input[_builtins.str] data: Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        :param pulumi.Input[_builtins.str] name: Unique channel name.
        """
        if data is not None:
            pulumi.set(__self__, "data", data)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        """
        return pulumi.get(self, "data")

    @data.setter
    def data(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique channel name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.type_token("signoz:index/notificationChannel:NotificationChannel")
class NotificationChannel(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A SigNoz notification channel (Slack, webhook, PagerDuty, email, OpsGenie, MS Teams). **Write operations require an admin Service Account token.** The receiver config goes in `data` as JSON.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_signoz_jooon as signoz

        # Notification channels require an ADMIN SigNoz service-account token.
        slack = signoz.NotificationChannel("slack",
            name="team-alerts",
            data=json.dumps({
                "slack_configs": [{
                    "send_resolved": True,
                    "api_url": "https://hooks.slack.com/services/T000/B000/XXXX",
                    "channel": "#alerts",
                }],
            }))
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] data: Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        :param pulumi.Input[_builtins.str] name: Unique channel name.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: NotificationChannelArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A SigNoz notification channel (Slack, webhook, PagerDuty, email, OpsGenie, MS Teams). **Write operations require an admin Service Account token.** The receiver config goes in `data` as JSON.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_signoz_jooon as signoz

        # Notification channels require an ADMIN SigNoz service-account token.
        slack = signoz.NotificationChannel("slack",
            name="team-alerts",
            data=json.dumps({
                "slack_configs": [{
                    "send_resolved": True,
                    "api_url": "https://hooks.slack.com/services/T000/B000/XXXX",
                    "channel": "#alerts",
                }],
            }))
        ```


        :param str resource_name: The name of the resource.
        :param NotificationChannelArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NotificationChannelArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NotificationChannelArgs.__new__(NotificationChannelArgs)

            if data is None and not opts.urn:
                raise TypeError("Missing required property 'data'")
            __props__.__dict__["data"] = data
            __props__.__dict__["name"] = name
        super(NotificationChannel, __self__).__init__(
            'signoz:index/notificationChannel:NotificationChannel',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            data: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None) -> 'NotificationChannel':
        """
        Get an existing NotificationChannel resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] data: Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        :param pulumi.Input[_builtins.str] name: Unique channel name.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _NotificationChannelState.__new__(_NotificationChannelState)

        __props__.__dict__["data"] = data
        __props__.__dict__["name"] = name
        return NotificationChannel(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Output[_builtins.str]:
        """
        Receiver configuration as JSON, e.g. `{"slack_configs":[{"api_url":"…","channel":"#alerts"}]}`. Compared semantically.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Unique channel name.
        """
        return pulumi.get(self, "name")

