# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SavedViewArgs', 'SavedView']

@pulumi.input_type
class SavedViewArgs:
    def __init__(__self__, *,
                 data: pulumi.Input[_builtins.str],
                 source_page: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a SavedView resource.

        :param pulumi.Input[_builtins.str] data: Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        :param pulumi.Input[_builtins.str] source_page: Explorer the view belongs to: `logs` or `traces`.
        :param pulumi.Input[_builtins.str] name: View name.
        """
        pulumi.set(__self__, "data", data)
        pulumi.set(__self__, "source_page", source_page)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Input[_builtins.str]:
        """
        Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        """
        return pulumi.get(self, "data")

    @data.setter
    def data(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "data", value)

    @_builtins.property
    @pulumi.getter(name="sourcePage")
    def source_page(self) -> pulumi.Input[_builtins.str]:
        """
        Explorer the view belongs to: `logs` or `traces`.
        """
        return pulumi.get(self, "source_page")

    @source_page.setter
    def source_page(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source_page", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        View name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _SavedViewState:
    def __init__(__self__, *,
                 data: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 source_page: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SavedView resources.

        :param pulumi.Input[_builtins.str] data: Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        :param pulumi.Input[_builtins.str] name: View name.
        :param pulumi.Input[_builtins.str] source_page: Explorer the view belongs to: `logs` or `traces`.
        """
        if data is not None:
            pulumi.set(__self__, "data", data)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if source_page is not None:
            pulumi.set(__self__, "source_page", source_page)

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        """
        return pulumi.get(self, "data")

    @data.setter
    def data(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        View name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="sourcePage")
    def source_page(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Explorer the view belongs to: `logs` or `traces`.
        """
        return pulumi.get(self, "source_page")

    @source_page.setter
    def source_page(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source_page", value)


@pulumi.type_token("signoz:index/savedView:SavedView")
class SavedView(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 source_page: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A saved SigNoz explorer view (logs or traces). The query state goes in `data` as JSON.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_signoz_jooon as signoz

        errors = signoz.SavedView("errors",
            name="Errors (last 15m)",
            source_page="logs",
            data=json.dumps({
                "compositeQuery": {
                    "queryType": "builder",
                    "panelType": "list",
                    "builderQueries": {
                        "A": {
                            "dataSource": "logs",
                            "queryName": "A",
                            "aggregateOperator": "noop",
                            "expression": "A",
                            "disabled": False,
                        },
                    },
                },
            }))
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] data: Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        :param pulumi.Input[_builtins.str] name: View name.
        :param pulumi.Input[_builtins.str] source_page: Explorer the view belongs to: `logs` or `traces`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SavedViewArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A saved SigNoz explorer view (logs or traces). The query state goes in `data` as JSON.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_signoz_jooon as signoz

        errors = signoz.SavedView("errors",
            name="Errors (last 15m)",
            source_page="logs",
            data=json.dumps({
                "compositeQuery": {
                    "queryType": "builder",
                    "panelType": "list",
                    "builderQueries": {
                        "A": {
                            "dataSource": "logs",
                            "queryName": "A",
                            "aggregateOperator": "noop",
                            "expression": "A",
                            "disabled": False,
                        },
                    },
                },
            }))
        ```


        :param str resource_name: The name of the resource.
        :param SavedViewArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SavedViewArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 source_page: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SavedViewArgs.__new__(SavedViewArgs)

            if data is None and not opts.urn:
                raise TypeError("Missing required property 'data'")
            __props__.__dict__["data"] = data
            __props__.__dict__["name"] = name
            if source_page is None and not opts.urn:
                raise TypeError("Missing required property 'source_page'")
            __props__.__dict__["source_page"] = source_page
        super(SavedView, __self__).__init__(
            'signoz:index/savedView:SavedView',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            data: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            source_page: pulumi.Input[Optional[_builtins.str]] = None) -> 'SavedView':
        """
        Get an existing SavedView resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] data: Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        :param pulumi.Input[_builtins.str] name: View name.
        :param pulumi.Input[_builtins.str] source_page: Explorer the view belongs to: `logs` or `traces`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SavedViewState.__new__(_SavedViewState)

        __props__.__dict__["data"] = data
        __props__.__dict__["name"] = name
        __props__.__dict__["source_page"] = source_page
        return SavedView(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Output[_builtins.str]:
        """
        Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        View name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="sourcePage")
    def source_page(self) -> pulumi.Output[_builtins.str]:
        """
        Explorer the view belongs to: `logs` or `traces`.
        """
        return pulumi.get(self, "source_page")

