// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"errors"
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A SigNoz alert rule. Top-level fields are typed; the query `condition`, `evaluation`, and `notificationSettings` are JSON blobs (export from the SigNoz UI to adapt). Defaults target the v5 / v2alpha1 schema required by SigNoz >= 0.125.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal(map[string]interface{}{
//				"compositeQuery": map[string]interface{}{
//					"queryType": "builder",
//					"panelType": "graph",
//					"queries": []map[string]interface{}{
//						map[string]interface{}{
//							"type": "builder_query",
//							"spec": map[string]interface{}{
//								"name":         "A",
//								"signal":       "logs",
//								"stepInterval": 0,
//								"aggregations": []map[string]interface{}{
//									map[string]interface{}{
//										"expression": "count()",
//									},
//								},
//								"filter": map[string]interface{}{
//									"expression": "severity_text = 'ERROR'",
//								},
//								"having": map[string]interface{}{
//									"expression": "",
//								},
//							},
//						},
//					},
//				},
//				"selectedQueryName": "A",
//				"thresholds": map[string]interface{}{
//					"kind": "basic",
//					"spec": []map[string]interface{}{
//						map[string]interface{}{
//							"name":      "warning",
//							"target":    100,
//							"matchType": "1",
//							"op":        "1",
//							"channels": []interface{}{
//								slack.Name,
//							},
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			tmpJSON1, err := json.Marshal(map[string]interface{}{
//				"kind": "rolling",
//				"spec": map[string]interface{}{
//					"evalWindow": "5m0s",
//					"frequency":  "1m0s",
//				},
//			})
//			if err != nil {
//				return err
//			}
//			json1 := string(tmpJSON1)
//			// A logs-based alert on the v5 / v2alpha1 schema (SigNoz >= 0.125).
//			// The threshold references a notification channel by name.
//			_, err = signoz.NewAlert(ctx, "high_error_logs", &signoz.AlertArgs{
//				Alert:      pulumi.String("High error log volume"),
//				AlertType:  pulumi.String("LOGS_BASED_ALERT"),
//				Severity:   pulumi.String("warning"),
//				Condition:  pulumi.String(pulumi.String(json0)),
//				Evaluation: pulumi.String(pulumi.String(json1)),
//				PreferredChannels: pulumi.StringArray{
//					slack.Name,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Alert struct {
	pulumi.CustomResourceState

	// Alert name.
	Alert pulumi.StringOutput `pulumi:"alert"`
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType pulumi.StringOutput `pulumi:"alertType"`
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition pulumi.StringOutput `pulumi:"condition"`
	// Human-readable description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether the rule is disabled. Defaults to false.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// Evaluation window (e.g. `5m0s`).
	EvalWindow pulumi.StringOutput `pulumi:"evalWindow"`
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation pulumi.StringPtrOutput `pulumi:"evaluation"`
	// Evaluation frequency (e.g. `1m0s`).
	Frequency pulumi.StringOutput `pulumi:"frequency"`
	// Custom labels attached to the alert.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
	NotificationSettings pulumi.StringPtrOutput `pulumi:"notificationSettings"`
	// Notification channel names the alert routes to.
	PreferredChannels pulumi.StringArrayOutput `pulumi:"preferredChannels"`
	// Rule engine type: `thresholdRule` (default) or `promqlRule`.
	RuleType pulumi.StringOutput `pulumi:"ruleType"`
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion pulumi.StringOutput `pulumi:"schemaVersion"`
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity pulumi.StringPtrOutput `pulumi:"severity"`
	// Source URL recorded on the rule.
	Source pulumi.StringPtrOutput `pulumi:"source"`
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewAlert registers a new resource with the given unique name, arguments, and options.
func NewAlert(ctx *pulumi.Context,
	name string, args *AlertArgs, opts ...pulumi.ResourceOption) (*Alert, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Alert == nil {
		return nil, errors.New("invalid value for required argument 'Alert'")
	}
	if args.AlertType == nil {
		return nil, errors.New("invalid value for required argument 'AlertType'")
	}
	if args.Condition == nil {
		return nil, errors.New("invalid value for required argument 'Condition'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Alert
	err := ctx.RegisterResource("signoz:index/alert:Alert", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAlert gets an existing Alert resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAlert(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AlertState, opts ...pulumi.ResourceOption) (*Alert, error) {
	var resource Alert
	err := ctx.ReadResource("signoz:index/alert:Alert", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Alert resources.
type alertState struct {
	// Alert name.
	Alert *string `pulumi:"alert"`
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType *string `pulumi:"alertType"`
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition *string `pulumi:"condition"`
	// Human-readable description.
	Description *string `pulumi:"description"`
	// Whether the rule is disabled. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Evaluation window (e.g. `5m0s`).
	EvalWindow *string `pulumi:"evalWindow"`
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation *string `pulumi:"evaluation"`
	// Evaluation frequency (e.g. `1m0s`).
	Frequency *string `pulumi:"frequency"`
	// Custom labels attached to the alert.
	Labels map[string]string `pulumi:"labels"`
	// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
	NotificationSettings *string `pulumi:"notificationSettings"`
	// Notification channel names the alert routes to.
	PreferredChannels []string `pulumi:"preferredChannels"`
	// Rule engine type: `thresholdRule` (default) or `promqlRule`.
	RuleType *string `pulumi:"ruleType"`
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion *string `pulumi:"schemaVersion"`
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity *string `pulumi:"severity"`
	// Source URL recorded on the rule.
	Source *string `pulumi:"source"`
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version *string `pulumi:"version"`
}

type AlertState struct {
	// Alert name.
	Alert pulumi.StringPtrInput
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType pulumi.StringPtrInput
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition pulumi.StringPtrInput
	// Human-readable description.
	Description pulumi.StringPtrInput
	// Whether the rule is disabled. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Evaluation window (e.g. `5m0s`).
	EvalWindow pulumi.StringPtrInput
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation pulumi.StringPtrInput
	// Evaluation frequency (e.g. `1m0s`).
	Frequency pulumi.StringPtrInput
	// Custom labels attached to the alert.
	Labels pulumi.StringMapInput
	// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
	NotificationSettings pulumi.StringPtrInput
	// Notification channel names the alert routes to.
	PreferredChannels pulumi.StringArrayInput
	// Rule engine type: `thresholdRule` (default) or `promqlRule`.
	RuleType pulumi.StringPtrInput
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion pulumi.StringPtrInput
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity pulumi.StringPtrInput
	// Source URL recorded on the rule.
	Source pulumi.StringPtrInput
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version pulumi.StringPtrInput
}

func (AlertState) ElementType() reflect.Type {
	return reflect.TypeOf((*alertState)(nil)).Elem()
}

type alertArgs struct {
	// Alert name.
	Alert string `pulumi:"alert"`
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType string `pulumi:"alertType"`
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition string `pulumi:"condition"`
	// Human-readable description.
	Description *string `pulumi:"description"`
	// Whether the rule is disabled. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Evaluation window (e.g. `5m0s`).
	EvalWindow *string `pulumi:"evalWindow"`
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation *string `pulumi:"evaluation"`
	// Evaluation frequency (e.g. `1m0s`).
	Frequency *string `pulumi:"frequency"`
	// Custom labels attached to the alert.
	Labels map[string]string `pulumi:"labels"`
	// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
	NotificationSettings *string `pulumi:"notificationSettings"`
	// Notification channel names the alert routes to.
	PreferredChannels []string `pulumi:"preferredChannels"`
	// Rule engine type: `thresholdRule` (default) or `promqlRule`.
	RuleType *string `pulumi:"ruleType"`
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion *string `pulumi:"schemaVersion"`
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity *string `pulumi:"severity"`
	// Source URL recorded on the rule.
	Source *string `pulumi:"source"`
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a Alert resource.
type AlertArgs struct {
	// Alert name.
	Alert pulumi.StringInput
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType pulumi.StringInput
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition pulumi.StringInput
	// Human-readable description.
	Description pulumi.StringPtrInput
	// Whether the rule is disabled. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Evaluation window (e.g. `5m0s`).
	EvalWindow pulumi.StringPtrInput
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation pulumi.StringPtrInput
	// Evaluation frequency (e.g. `1m0s`).
	Frequency pulumi.StringPtrInput
	// Custom labels attached to the alert.
	Labels pulumi.StringMapInput
	// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
	NotificationSettings pulumi.StringPtrInput
	// Notification channel names the alert routes to.
	PreferredChannels pulumi.StringArrayInput
	// Rule engine type: `thresholdRule` (default) or `promqlRule`.
	RuleType pulumi.StringPtrInput
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion pulumi.StringPtrInput
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity pulumi.StringPtrInput
	// Source URL recorded on the rule.
	Source pulumi.StringPtrInput
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version pulumi.StringPtrInput
}

func (AlertArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*alertArgs)(nil)).Elem()
}

type AlertInput interface {
	pulumi.Input

	ToAlertOutput() AlertOutput
	ToAlertOutputWithContext(ctx context.Context) AlertOutput
}

func (*Alert) ElementType() reflect.Type {
	return reflect.TypeOf((**Alert)(nil)).Elem()
}

func (i *Alert) ToAlertOutput() AlertOutput {
	return i.ToAlertOutputWithContext(context.Background())
}

func (i *Alert) ToAlertOutputWithContext(ctx context.Context) AlertOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlertOutput)
}

// AlertArrayInput is an input type that accepts AlertArray and AlertArrayOutput values.
// You can construct a concrete instance of `AlertArrayInput` via:
//
//	AlertArray{ AlertArgs{...} }
type AlertArrayInput interface {
	pulumi.Input

	ToAlertArrayOutput() AlertArrayOutput
	ToAlertArrayOutputWithContext(context.Context) AlertArrayOutput
}

type AlertArray []AlertInput

func (AlertArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Alert)(nil)).Elem()
}

func (i AlertArray) ToAlertArrayOutput() AlertArrayOutput {
	return i.ToAlertArrayOutputWithContext(context.Background())
}

func (i AlertArray) ToAlertArrayOutputWithContext(ctx context.Context) AlertArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlertArrayOutput)
}

// AlertMapInput is an input type that accepts AlertMap and AlertMapOutput values.
// You can construct a concrete instance of `AlertMapInput` via:
//
//	AlertMap{ "key": AlertArgs{...} }
type AlertMapInput interface {
	pulumi.Input

	ToAlertMapOutput() AlertMapOutput
	ToAlertMapOutputWithContext(context.Context) AlertMapOutput
}

type AlertMap map[string]AlertInput

func (AlertMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Alert)(nil)).Elem()
}

func (i AlertMap) ToAlertMapOutput() AlertMapOutput {
	return i.ToAlertMapOutputWithContext(context.Background())
}

func (i AlertMap) ToAlertMapOutputWithContext(ctx context.Context) AlertMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlertMapOutput)
}

type AlertOutput struct{ *pulumi.OutputState }

func (AlertOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Alert)(nil)).Elem()
}

func (o AlertOutput) ToAlertOutput() AlertOutput {
	return o
}

func (o AlertOutput) ToAlertOutputWithContext(ctx context.Context) AlertOutput {
	return o
}

// Alert name.
func (o AlertOutput) Alert() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Alert }).(pulumi.StringOutput)
}

// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
func (o AlertOutput) AlertType() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.AlertType }).(pulumi.StringOutput)
}

// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
func (o AlertOutput) Condition() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Condition }).(pulumi.StringOutput)
}

// Human-readable description.
func (o AlertOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether the rule is disabled. Defaults to false.
func (o AlertOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Alert) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// Evaluation window (e.g. `5m0s`).
func (o AlertOutput) EvalWindow() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.EvalWindow }).(pulumi.StringOutput)
}

// Evaluation block as JSON (v2alpha1+). Compared semantically.
func (o AlertOutput) Evaluation() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringPtrOutput { return v.Evaluation }).(pulumi.StringPtrOutput)
}

// Evaluation frequency (e.g. `1m0s`).
func (o AlertOutput) Frequency() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Frequency }).(pulumi.StringOutput)
}

// Custom labels attached to the alert.
func (o AlertOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
func (o AlertOutput) NotificationSettings() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringPtrOutput { return v.NotificationSettings }).(pulumi.StringPtrOutput)
}

// Notification channel names the alert routes to.
func (o AlertOutput) PreferredChannels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringArrayOutput { return v.PreferredChannels }).(pulumi.StringArrayOutput)
}

// Rule engine type: `thresholdRule` (default) or `promqlRule`.
func (o AlertOutput) RuleType() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.RuleType }).(pulumi.StringOutput)
}

// Alert schema version. Defaults to `v2alpha1`.
func (o AlertOutput) SchemaVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.SchemaVersion }).(pulumi.StringOutput)
}

// Severity label (e.g. `info`, `warning`, `critical`).
func (o AlertOutput) Severity() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringPtrOutput { return v.Severity }).(pulumi.StringPtrOutput)
}

// Source URL recorded on the rule.
func (o AlertOutput) Source() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringPtrOutput { return v.Source }).(pulumi.StringPtrOutput)
}

// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
func (o AlertOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type AlertArrayOutput struct{ *pulumi.OutputState }

func (AlertArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Alert)(nil)).Elem()
}

func (o AlertArrayOutput) ToAlertArrayOutput() AlertArrayOutput {
	return o
}

func (o AlertArrayOutput) ToAlertArrayOutputWithContext(ctx context.Context) AlertArrayOutput {
	return o
}

func (o AlertArrayOutput) Index(i pulumi.IntInput) AlertOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Alert {
		return vs[0].([]*Alert)[vs[1].(int)]
	}).(AlertOutput)
}

type AlertMapOutput struct{ *pulumi.OutputState }

func (AlertMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Alert)(nil)).Elem()
}

func (o AlertMapOutput) ToAlertMapOutput() AlertMapOutput {
	return o
}

func (o AlertMapOutput) ToAlertMapOutputWithContext(ctx context.Context) AlertMapOutput {
	return o
}

func (o AlertMapOutput) MapIndex(k pulumi.StringInput) AlertOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Alert {
		return vs[0].(map[string]*Alert)[vs[1].(string)]
	}).(AlertOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AlertInput)(nil)).Elem(), &Alert{})
	pulumi.RegisterInputType(reflect.TypeOf((*AlertArrayInput)(nil)).Elem(), AlertArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AlertMapInput)(nil)).Elem(), AlertMap{})
	pulumi.RegisterOutputType(AlertOutput{})
	pulumi.RegisterOutputType(AlertArrayOutput{})
	pulumi.RegisterOutputType(AlertMapOutput{})
}
