// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"errors"
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Alert struct {
	pulumi.CustomResourceState

	// Name of the alert.
	Alert pulumi.StringOutput `pulumi:"alert"`
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType pulumi.StringOutput `pulumi:"alertType"`
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	//
	// Deprecated: This field is no longer needed and will be ignored
	BroadcastToAll pulumi.BoolOutput `pulumi:"broadcastToAll"`
	// Condition of the alert.
	Condition pulumi.StringOutput `pulumi:"condition"`
	// Creation time of the alert.
	CreateAt pulumi.StringOutput `pulumi:"createAt"`
	// Creator of the alert.
	CreateBy pulumi.StringOutput `pulumi:"createBy"`
	// Description of the alert.
	Description pulumi.StringOutput `pulumi:"description"`
	// Whether the alert is disabled.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow pulumi.StringOutput `pulumi:"evalWindow"`
	// Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
	Evaluation pulumi.StringOutput `pulumi:"evaluation"`
	// The frequency of the alert. By default, it is 1m0s.
	Frequency pulumi.StringOutput `pulumi:"frequency"`
	// Labels of the alert. Severity is a required label.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Notification settings for the alert. Only used when schemaVersion is v2 or higher.
	NotificationSettings AlertNotificationSettingsOutput `pulumi:"notificationSettings"`
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels pulumi.StringArrayOutput `pulumi:"preferredChannels"`
	// Type of the alert. Possible values are: thresholdRule and promql_rule.
	RuleType pulumi.StringOutput `pulumi:"ruleType"`
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
	SchemaVersion pulumi.StringOutput `pulumi:"schemaVersion"`
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity pulumi.StringOutput `pulumi:"severity"`
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source pulumi.StringOutput `pulumi:"source"`
	// State of the alert.
	State pulumi.StringOutput `pulumi:"state"`
	// Summary of the alert.
	Summary pulumi.StringOutput `pulumi:"summary"`
	// Last update time of the alert.
	UpdateAt pulumi.StringOutput `pulumi:"updateAt"`
	// Last updater of the alert.
	UpdateBy pulumi.StringOutput `pulumi:"updateBy"`
	// Version of the alert. By default, it is v4.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewAlert registers a new resource with the given unique name, arguments, and options.
func NewAlert(ctx *pulumi.Context,
	name string, args *AlertArgs, opts ...pulumi.ResourceOption) (*Alert, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Alert == nil {
		return nil, errors.New("invalid value for required argument 'Alert'")
	}
	if args.AlertType == nil {
		return nil, errors.New("invalid value for required argument 'AlertType'")
	}
	if args.Condition == nil {
		return nil, errors.New("invalid value for required argument 'Condition'")
	}
	if args.Severity == nil {
		return nil, errors.New("invalid value for required argument 'Severity'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Alert
	err := ctx.RegisterResource("signoz:index/alert:Alert", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAlert gets an existing Alert resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAlert(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AlertState, opts ...pulumi.ResourceOption) (*Alert, error) {
	var resource Alert
	err := ctx.ReadResource("signoz:index/alert:Alert", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Alert resources.
type alertState struct {
	// Name of the alert.
	Alert *string `pulumi:"alert"`
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType *string `pulumi:"alertType"`
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	//
	// Deprecated: This field is no longer needed and will be ignored
	BroadcastToAll *bool `pulumi:"broadcastToAll"`
	// Condition of the alert.
	Condition *string `pulumi:"condition"`
	// Creation time of the alert.
	CreateAt *string `pulumi:"createAt"`
	// Creator of the alert.
	CreateBy *string `pulumi:"createBy"`
	// Description of the alert.
	Description *string `pulumi:"description"`
	// Whether the alert is disabled.
	Disabled *bool `pulumi:"disabled"`
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow *string `pulumi:"evalWindow"`
	// Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
	Evaluation *string `pulumi:"evaluation"`
	// The frequency of the alert. By default, it is 1m0s.
	Frequency *string `pulumi:"frequency"`
	// Labels of the alert. Severity is a required label.
	Labels map[string]string `pulumi:"labels"`
	// Notification settings for the alert. Only used when schemaVersion is v2 or higher.
	NotificationSettings *AlertNotificationSettings `pulumi:"notificationSettings"`
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels []string `pulumi:"preferredChannels"`
	// Type of the alert. Possible values are: thresholdRule and promql_rule.
	RuleType *string `pulumi:"ruleType"`
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
	SchemaVersion *string `pulumi:"schemaVersion"`
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity *string `pulumi:"severity"`
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source *string `pulumi:"source"`
	// State of the alert.
	State *string `pulumi:"state"`
	// Summary of the alert.
	Summary *string `pulumi:"summary"`
	// Last update time of the alert.
	UpdateAt *string `pulumi:"updateAt"`
	// Last updater of the alert.
	UpdateBy *string `pulumi:"updateBy"`
	// Version of the alert. By default, it is v4.
	Version *string `pulumi:"version"`
}

type AlertState struct {
	// Name of the alert.
	Alert pulumi.StringPtrInput
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType pulumi.StringPtrInput
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	//
	// Deprecated: This field is no longer needed and will be ignored
	BroadcastToAll pulumi.BoolPtrInput
	// Condition of the alert.
	Condition pulumi.StringPtrInput
	// Creation time of the alert.
	CreateAt pulumi.StringPtrInput
	// Creator of the alert.
	CreateBy pulumi.StringPtrInput
	// Description of the alert.
	Description pulumi.StringPtrInput
	// Whether the alert is disabled.
	Disabled pulumi.BoolPtrInput
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow pulumi.StringPtrInput
	// Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
	Evaluation pulumi.StringPtrInput
	// The frequency of the alert. By default, it is 1m0s.
	Frequency pulumi.StringPtrInput
	// Labels of the alert. Severity is a required label.
	Labels pulumi.StringMapInput
	// Notification settings for the alert. Only used when schemaVersion is v2 or higher.
	NotificationSettings AlertNotificationSettingsPtrInput
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels pulumi.StringArrayInput
	// Type of the alert. Possible values are: thresholdRule and promql_rule.
	RuleType pulumi.StringPtrInput
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
	SchemaVersion pulumi.StringPtrInput
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity pulumi.StringPtrInput
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source pulumi.StringPtrInput
	// State of the alert.
	State pulumi.StringPtrInput
	// Summary of the alert.
	Summary pulumi.StringPtrInput
	// Last update time of the alert.
	UpdateAt pulumi.StringPtrInput
	// Last updater of the alert.
	UpdateBy pulumi.StringPtrInput
	// Version of the alert. By default, it is v4.
	Version pulumi.StringPtrInput
}

func (AlertState) ElementType() reflect.Type {
	return reflect.TypeOf((*alertState)(nil)).Elem()
}

type alertArgs struct {
	// Name of the alert.
	Alert string `pulumi:"alert"`
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType string `pulumi:"alertType"`
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	//
	// Deprecated: This field is no longer needed and will be ignored
	BroadcastToAll *bool `pulumi:"broadcastToAll"`
	// Condition of the alert.
	Condition string `pulumi:"condition"`
	// Description of the alert.
	Description *string `pulumi:"description"`
	// Whether the alert is disabled.
	Disabled *bool `pulumi:"disabled"`
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow *string `pulumi:"evalWindow"`
	// Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
	Evaluation *string `pulumi:"evaluation"`
	// The frequency of the alert. By default, it is 1m0s.
	Frequency *string `pulumi:"frequency"`
	// Labels of the alert. Severity is a required label.
	Labels map[string]string `pulumi:"labels"`
	// Notification settings for the alert. Only used when schemaVersion is v2 or higher.
	NotificationSettings *AlertNotificationSettings `pulumi:"notificationSettings"`
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels []string `pulumi:"preferredChannels"`
	// Type of the alert. Possible values are: thresholdRule and promql_rule.
	RuleType *string `pulumi:"ruleType"`
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
	SchemaVersion *string `pulumi:"schemaVersion"`
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity string `pulumi:"severity"`
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source *string `pulumi:"source"`
	// Summary of the alert.
	Summary *string `pulumi:"summary"`
	// Version of the alert. By default, it is v4.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a Alert resource.
type AlertArgs struct {
	// Name of the alert.
	Alert pulumi.StringInput
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType pulumi.StringInput
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	//
	// Deprecated: This field is no longer needed and will be ignored
	BroadcastToAll pulumi.BoolPtrInput
	// Condition of the alert.
	Condition pulumi.StringInput
	// Description of the alert.
	Description pulumi.StringPtrInput
	// Whether the alert is disabled.
	Disabled pulumi.BoolPtrInput
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow pulumi.StringPtrInput
	// Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
	Evaluation pulumi.StringPtrInput
	// The frequency of the alert. By default, it is 1m0s.
	Frequency pulumi.StringPtrInput
	// Labels of the alert. Severity is a required label.
	Labels pulumi.StringMapInput
	// Notification settings for the alert. Only used when schemaVersion is v2 or higher.
	NotificationSettings AlertNotificationSettingsPtrInput
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels pulumi.StringArrayInput
	// Type of the alert. Possible values are: thresholdRule and promql_rule.
	RuleType pulumi.StringPtrInput
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
	SchemaVersion pulumi.StringPtrInput
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity pulumi.StringInput
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source pulumi.StringPtrInput
	// Summary of the alert.
	Summary pulumi.StringPtrInput
	// Version of the alert. By default, it is v4.
	Version pulumi.StringPtrInput
}

func (AlertArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*alertArgs)(nil)).Elem()
}

type AlertInput interface {
	pulumi.Input

	ToAlertOutput() AlertOutput
	ToAlertOutputWithContext(ctx context.Context) AlertOutput
}

func (*Alert) ElementType() reflect.Type {
	return reflect.TypeOf((**Alert)(nil)).Elem()
}

func (i *Alert) ToAlertOutput() AlertOutput {
	return i.ToAlertOutputWithContext(context.Background())
}

func (i *Alert) ToAlertOutputWithContext(ctx context.Context) AlertOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlertOutput)
}

// AlertArrayInput is an input type that accepts AlertArray and AlertArrayOutput values.
// You can construct a concrete instance of `AlertArrayInput` via:
//
//	AlertArray{ AlertArgs{...} }
type AlertArrayInput interface {
	pulumi.Input

	ToAlertArrayOutput() AlertArrayOutput
	ToAlertArrayOutputWithContext(context.Context) AlertArrayOutput
}

type AlertArray []AlertInput

func (AlertArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Alert)(nil)).Elem()
}

func (i AlertArray) ToAlertArrayOutput() AlertArrayOutput {
	return i.ToAlertArrayOutputWithContext(context.Background())
}

func (i AlertArray) ToAlertArrayOutputWithContext(ctx context.Context) AlertArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlertArrayOutput)
}

// AlertMapInput is an input type that accepts AlertMap and AlertMapOutput values.
// You can construct a concrete instance of `AlertMapInput` via:
//
//	AlertMap{ "key": AlertArgs{...} }
type AlertMapInput interface {
	pulumi.Input

	ToAlertMapOutput() AlertMapOutput
	ToAlertMapOutputWithContext(context.Context) AlertMapOutput
}

type AlertMap map[string]AlertInput

func (AlertMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Alert)(nil)).Elem()
}

func (i AlertMap) ToAlertMapOutput() AlertMapOutput {
	return i.ToAlertMapOutputWithContext(context.Background())
}

func (i AlertMap) ToAlertMapOutputWithContext(ctx context.Context) AlertMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlertMapOutput)
}

type AlertOutput struct{ *pulumi.OutputState }

func (AlertOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Alert)(nil)).Elem()
}

func (o AlertOutput) ToAlertOutput() AlertOutput {
	return o
}

func (o AlertOutput) ToAlertOutputWithContext(ctx context.Context) AlertOutput {
	return o
}

// Name of the alert.
func (o AlertOutput) Alert() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Alert }).(pulumi.StringOutput)
}

// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
func (o AlertOutput) AlertType() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.AlertType }).(pulumi.StringOutput)
}

// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
//
// Deprecated: This field is no longer needed and will be ignored
func (o AlertOutput) BroadcastToAll() pulumi.BoolOutput {
	return o.ApplyT(func(v *Alert) pulumi.BoolOutput { return v.BroadcastToAll }).(pulumi.BoolOutput)
}

// Condition of the alert.
func (o AlertOutput) Condition() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Condition }).(pulumi.StringOutput)
}

// Creation time of the alert.
func (o AlertOutput) CreateAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.CreateAt }).(pulumi.StringOutput)
}

// Creator of the alert.
func (o AlertOutput) CreateBy() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.CreateBy }).(pulumi.StringOutput)
}

// Description of the alert.
func (o AlertOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Whether the alert is disabled.
func (o AlertOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Alert) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// The evaluation window of the alert. By default, it is 5m0s.
func (o AlertOutput) EvalWindow() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.EvalWindow }).(pulumi.StringOutput)
}

// Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
func (o AlertOutput) Evaluation() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Evaluation }).(pulumi.StringOutput)
}

// The frequency of the alert. By default, it is 1m0s.
func (o AlertOutput) Frequency() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Frequency }).(pulumi.StringOutput)
}

// Labels of the alert. Severity is a required label.
func (o AlertOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Notification settings for the alert. Only used when schemaVersion is v2 or higher.
func (o AlertOutput) NotificationSettings() AlertNotificationSettingsOutput {
	return o.ApplyT(func(v *Alert) AlertNotificationSettingsOutput { return v.NotificationSettings }).(AlertNotificationSettingsOutput)
}

// Preferred channels of the alert. By default, it is empty.
func (o AlertOutput) PreferredChannels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringArrayOutput { return v.PreferredChannels }).(pulumi.StringArrayOutput)
}

// Type of the alert. Possible values are: thresholdRule and promql_rule.
func (o AlertOutput) RuleType() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.RuleType }).(pulumi.StringOutput)
}

// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
func (o AlertOutput) SchemaVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.SchemaVersion }).(pulumi.StringOutput)
}

// Severity of the alert. Possible values are: info, warning, error, and critical.
func (o AlertOutput) Severity() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Severity }).(pulumi.StringOutput)
}

// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
func (o AlertOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// State of the alert.
func (o AlertOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// Summary of the alert.
func (o AlertOutput) Summary() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Summary }).(pulumi.StringOutput)
}

// Last update time of the alert.
func (o AlertOutput) UpdateAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.UpdateAt }).(pulumi.StringOutput)
}

// Last updater of the alert.
func (o AlertOutput) UpdateBy() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.UpdateBy }).(pulumi.StringOutput)
}

// Version of the alert. By default, it is v4.
func (o AlertOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Alert) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type AlertArrayOutput struct{ *pulumi.OutputState }

func (AlertArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Alert)(nil)).Elem()
}

func (o AlertArrayOutput) ToAlertArrayOutput() AlertArrayOutput {
	return o
}

func (o AlertArrayOutput) ToAlertArrayOutputWithContext(ctx context.Context) AlertArrayOutput {
	return o
}

func (o AlertArrayOutput) Index(i pulumi.IntInput) AlertOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Alert {
		return vs[0].([]*Alert)[vs[1].(int)]
	}).(AlertOutput)
}

type AlertMapOutput struct{ *pulumi.OutputState }

func (AlertMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Alert)(nil)).Elem()
}

func (o AlertMapOutput) ToAlertMapOutput() AlertMapOutput {
	return o
}

func (o AlertMapOutput) ToAlertMapOutputWithContext(ctx context.Context) AlertMapOutput {
	return o
}

func (o AlertMapOutput) MapIndex(k pulumi.StringInput) AlertOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Alert {
		return vs[0].(map[string]*Alert)[vs[1].(string)]
	}).(AlertOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AlertInput)(nil)).Elem(), &Alert{})
	pulumi.RegisterInputType(reflect.TypeOf((*AlertArrayInput)(nil)).Elem(), AlertArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AlertMapInput)(nil)).Elem(), AlertMap{})
	pulumi.RegisterOutputType(AlertOutput{})
	pulumi.RegisterOutputType(AlertArrayOutput{})
	pulumi.RegisterOutputType(AlertMapOutput{})
}
