// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"errors"
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Dashboard struct {
	pulumi.CustomResourceState

	CollapsableRowsMigrated pulumi.BoolOutput `pulumi:"collapsableRowsMigrated"`
	// Creation time of the dashboard.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Creator of the dashboard.
	CreatedBy pulumi.StringOutput `pulumi:"createdBy"`
	// Description of the dashboard.
	Description pulumi.StringOutput `pulumi:"description"`
	// Layout of the dashboard.
	Layout pulumi.StringOutput `pulumi:"layout"`
	// Name of the dashboard.
	Name     pulumi.StringOutput    `pulumi:"name"`
	PanelMap pulumi.StringPtrOutput `pulumi:"panelMap"`
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source pulumi.StringOutput `pulumi:"source"`
	// Tags of the dashboard.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// Title of the dashboard.
	Title pulumi.StringOutput `pulumi:"title"`
	// Last update time of the dashboard.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Last updater of the dashboard.
	UpdatedBy       pulumi.StringOutput `pulumi:"updatedBy"`
	UploadedGrafana pulumi.BoolOutput   `pulumi:"uploadedGrafana"`
	// Variables for the dashboard.
	Variables pulumi.StringOutput `pulumi:"variables"`
	// Version of the dashboard.
	Version pulumi.StringOutput `pulumi:"version"`
	// Widgets for the dashboard.
	Widgets pulumi.StringOutput `pulumi:"widgets"`
}

// NewDashboard registers a new resource with the given unique name, arguments, and options.
func NewDashboard(ctx *pulumi.Context,
	name string, args *DashboardArgs, opts ...pulumi.ResourceOption) (*Dashboard, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CollapsableRowsMigrated == nil {
		return nil, errors.New("invalid value for required argument 'CollapsableRowsMigrated'")
	}
	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.Layout == nil {
		return nil, errors.New("invalid value for required argument 'Layout'")
	}
	if args.Title == nil {
		return nil, errors.New("invalid value for required argument 'Title'")
	}
	if args.UploadedGrafana == nil {
		return nil, errors.New("invalid value for required argument 'UploadedGrafana'")
	}
	if args.Variables == nil {
		return nil, errors.New("invalid value for required argument 'Variables'")
	}
	if args.Version == nil {
		return nil, errors.New("invalid value for required argument 'Version'")
	}
	if args.Widgets == nil {
		return nil, errors.New("invalid value for required argument 'Widgets'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Dashboard
	err := ctx.RegisterResource("signoz:index/dashboard:Dashboard", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDashboard gets an existing Dashboard resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDashboard(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DashboardState, opts ...pulumi.ResourceOption) (*Dashboard, error) {
	var resource Dashboard
	err := ctx.ReadResource("signoz:index/dashboard:Dashboard", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Dashboard resources.
type dashboardState struct {
	CollapsableRowsMigrated *bool `pulumi:"collapsableRowsMigrated"`
	// Creation time of the dashboard.
	CreatedAt *string `pulumi:"createdAt"`
	// Creator of the dashboard.
	CreatedBy *string `pulumi:"createdBy"`
	// Description of the dashboard.
	Description *string `pulumi:"description"`
	// Layout of the dashboard.
	Layout *string `pulumi:"layout"`
	// Name of the dashboard.
	Name     *string `pulumi:"name"`
	PanelMap *string `pulumi:"panelMap"`
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source *string `pulumi:"source"`
	// Tags of the dashboard.
	Tags []string `pulumi:"tags"`
	// Title of the dashboard.
	Title *string `pulumi:"title"`
	// Last update time of the dashboard.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Last updater of the dashboard.
	UpdatedBy       *string `pulumi:"updatedBy"`
	UploadedGrafana *bool   `pulumi:"uploadedGrafana"`
	// Variables for the dashboard.
	Variables *string `pulumi:"variables"`
	// Version of the dashboard.
	Version *string `pulumi:"version"`
	// Widgets for the dashboard.
	Widgets *string `pulumi:"widgets"`
}

type DashboardState struct {
	CollapsableRowsMigrated pulumi.BoolPtrInput
	// Creation time of the dashboard.
	CreatedAt pulumi.StringPtrInput
	// Creator of the dashboard.
	CreatedBy pulumi.StringPtrInput
	// Description of the dashboard.
	Description pulumi.StringPtrInput
	// Layout of the dashboard.
	Layout pulumi.StringPtrInput
	// Name of the dashboard.
	Name     pulumi.StringPtrInput
	PanelMap pulumi.StringPtrInput
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source pulumi.StringPtrInput
	// Tags of the dashboard.
	Tags pulumi.StringArrayInput
	// Title of the dashboard.
	Title pulumi.StringPtrInput
	// Last update time of the dashboard.
	UpdatedAt pulumi.StringPtrInput
	// Last updater of the dashboard.
	UpdatedBy       pulumi.StringPtrInput
	UploadedGrafana pulumi.BoolPtrInput
	// Variables for the dashboard.
	Variables pulumi.StringPtrInput
	// Version of the dashboard.
	Version pulumi.StringPtrInput
	// Widgets for the dashboard.
	Widgets pulumi.StringPtrInput
}

func (DashboardState) ElementType() reflect.Type {
	return reflect.TypeOf((*dashboardState)(nil)).Elem()
}

type dashboardArgs struct {
	CollapsableRowsMigrated bool `pulumi:"collapsableRowsMigrated"`
	// Description of the dashboard.
	Description string `pulumi:"description"`
	// Layout of the dashboard.
	Layout string `pulumi:"layout"`
	// Name of the dashboard.
	Name     *string `pulumi:"name"`
	PanelMap *string `pulumi:"panelMap"`
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source *string `pulumi:"source"`
	// Tags of the dashboard.
	Tags []string `pulumi:"tags"`
	// Title of the dashboard.
	Title           string `pulumi:"title"`
	UploadedGrafana bool   `pulumi:"uploadedGrafana"`
	// Variables for the dashboard.
	Variables string `pulumi:"variables"`
	// Version of the dashboard.
	Version string `pulumi:"version"`
	// Widgets for the dashboard.
	Widgets string `pulumi:"widgets"`
}

// The set of arguments for constructing a Dashboard resource.
type DashboardArgs struct {
	CollapsableRowsMigrated pulumi.BoolInput
	// Description of the dashboard.
	Description pulumi.StringInput
	// Layout of the dashboard.
	Layout pulumi.StringInput
	// Name of the dashboard.
	Name     pulumi.StringPtrInput
	PanelMap pulumi.StringPtrInput
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source pulumi.StringPtrInput
	// Tags of the dashboard.
	Tags pulumi.StringArrayInput
	// Title of the dashboard.
	Title           pulumi.StringInput
	UploadedGrafana pulumi.BoolInput
	// Variables for the dashboard.
	Variables pulumi.StringInput
	// Version of the dashboard.
	Version pulumi.StringInput
	// Widgets for the dashboard.
	Widgets pulumi.StringInput
}

func (DashboardArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dashboardArgs)(nil)).Elem()
}

type DashboardInput interface {
	pulumi.Input

	ToDashboardOutput() DashboardOutput
	ToDashboardOutputWithContext(ctx context.Context) DashboardOutput
}

func (*Dashboard) ElementType() reflect.Type {
	return reflect.TypeOf((**Dashboard)(nil)).Elem()
}

func (i *Dashboard) ToDashboardOutput() DashboardOutput {
	return i.ToDashboardOutputWithContext(context.Background())
}

func (i *Dashboard) ToDashboardOutputWithContext(ctx context.Context) DashboardOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DashboardOutput)
}

// DashboardArrayInput is an input type that accepts DashboardArray and DashboardArrayOutput values.
// You can construct a concrete instance of `DashboardArrayInput` via:
//
//	DashboardArray{ DashboardArgs{...} }
type DashboardArrayInput interface {
	pulumi.Input

	ToDashboardArrayOutput() DashboardArrayOutput
	ToDashboardArrayOutputWithContext(context.Context) DashboardArrayOutput
}

type DashboardArray []DashboardInput

func (DashboardArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Dashboard)(nil)).Elem()
}

func (i DashboardArray) ToDashboardArrayOutput() DashboardArrayOutput {
	return i.ToDashboardArrayOutputWithContext(context.Background())
}

func (i DashboardArray) ToDashboardArrayOutputWithContext(ctx context.Context) DashboardArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DashboardArrayOutput)
}

// DashboardMapInput is an input type that accepts DashboardMap and DashboardMapOutput values.
// You can construct a concrete instance of `DashboardMapInput` via:
//
//	DashboardMap{ "key": DashboardArgs{...} }
type DashboardMapInput interface {
	pulumi.Input

	ToDashboardMapOutput() DashboardMapOutput
	ToDashboardMapOutputWithContext(context.Context) DashboardMapOutput
}

type DashboardMap map[string]DashboardInput

func (DashboardMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Dashboard)(nil)).Elem()
}

func (i DashboardMap) ToDashboardMapOutput() DashboardMapOutput {
	return i.ToDashboardMapOutputWithContext(context.Background())
}

func (i DashboardMap) ToDashboardMapOutputWithContext(ctx context.Context) DashboardMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DashboardMapOutput)
}

type DashboardOutput struct{ *pulumi.OutputState }

func (DashboardOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Dashboard)(nil)).Elem()
}

func (o DashboardOutput) ToDashboardOutput() DashboardOutput {
	return o
}

func (o DashboardOutput) ToDashboardOutputWithContext(ctx context.Context) DashboardOutput {
	return o
}

func (o DashboardOutput) CollapsableRowsMigrated() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.BoolOutput { return v.CollapsableRowsMigrated }).(pulumi.BoolOutput)
}

// Creation time of the dashboard.
func (o DashboardOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Creator of the dashboard.
func (o DashboardOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.CreatedBy }).(pulumi.StringOutput)
}

// Description of the dashboard.
func (o DashboardOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Layout of the dashboard.
func (o DashboardOutput) Layout() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Layout }).(pulumi.StringOutput)
}

// Name of the dashboard.
func (o DashboardOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o DashboardOutput) PanelMap() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringPtrOutput { return v.PanelMap }).(pulumi.StringPtrOutput)
}

// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
func (o DashboardOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// Tags of the dashboard.
func (o DashboardOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// Title of the dashboard.
func (o DashboardOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Title }).(pulumi.StringOutput)
}

// Last update time of the dashboard.
func (o DashboardOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Last updater of the dashboard.
func (o DashboardOutput) UpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.UpdatedBy }).(pulumi.StringOutput)
}

func (o DashboardOutput) UploadedGrafana() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.BoolOutput { return v.UploadedGrafana }).(pulumi.BoolOutput)
}

// Variables for the dashboard.
func (o DashboardOutput) Variables() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Variables }).(pulumi.StringOutput)
}

// Version of the dashboard.
func (o DashboardOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

// Widgets for the dashboard.
func (o DashboardOutput) Widgets() pulumi.StringOutput {
	return o.ApplyT(func(v *Dashboard) pulumi.StringOutput { return v.Widgets }).(pulumi.StringOutput)
}

type DashboardArrayOutput struct{ *pulumi.OutputState }

func (DashboardArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Dashboard)(nil)).Elem()
}

func (o DashboardArrayOutput) ToDashboardArrayOutput() DashboardArrayOutput {
	return o
}

func (o DashboardArrayOutput) ToDashboardArrayOutputWithContext(ctx context.Context) DashboardArrayOutput {
	return o
}

func (o DashboardArrayOutput) Index(i pulumi.IntInput) DashboardOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Dashboard {
		return vs[0].([]*Dashboard)[vs[1].(int)]
	}).(DashboardOutput)
}

type DashboardMapOutput struct{ *pulumi.OutputState }

func (DashboardMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Dashboard)(nil)).Elem()
}

func (o DashboardMapOutput) ToDashboardMapOutput() DashboardMapOutput {
	return o
}

func (o DashboardMapOutput) ToDashboardMapOutputWithContext(ctx context.Context) DashboardMapOutput {
	return o
}

func (o DashboardMapOutput) MapIndex(k pulumi.StringInput) DashboardOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Dashboard {
		return vs[0].(map[string]*Dashboard)[vs[1].(string)]
	}).(DashboardOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DashboardInput)(nil)).Elem(), &Dashboard{})
	pulumi.RegisterInputType(reflect.TypeOf((*DashboardArrayInput)(nil)).Elem(), DashboardArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DashboardMapInput)(nil)).Elem(), DashboardMap{})
	pulumi.RegisterOutputType(DashboardOutput{})
	pulumi.RegisterOutputType(DashboardArrayOutput{})
	pulumi.RegisterOutputType(DashboardMapOutput{})
}
