// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAlert(ctx *pulumi.Context, args *LookupAlertArgs, opts ...pulumi.InvokeOption) (*LookupAlertResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAlertResult
	err := ctx.Invoke("signoz:index/getAlert:getAlert", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAlert.
type LookupAlertArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getAlert.
type LookupAlertResult struct {
	Alert     string `pulumi:"alert"`
	AlertType string `pulumi:"alertType"`
	// Deprecated: This field is no longer needed and will be ignored
	BroadcastToAll       bool                         `pulumi:"broadcastToAll"`
	Condition            string                       `pulumi:"condition"`
	Description          string                       `pulumi:"description"`
	Disabled             bool                         `pulumi:"disabled"`
	EvalWindow           string                       `pulumi:"evalWindow"`
	Evaluation           string                       `pulumi:"evaluation"`
	Frequency            string                       `pulumi:"frequency"`
	Id                   string                       `pulumi:"id"`
	Labels               map[string]string            `pulumi:"labels"`
	NotificationSettings GetAlertNotificationSettings `pulumi:"notificationSettings"`
	PreferredChannels    []string                     `pulumi:"preferredChannels"`
	RuleType             string                       `pulumi:"ruleType"`
	SchemaVersion        string                       `pulumi:"schemaVersion"`
	Severity             string                       `pulumi:"severity"`
	Source               string                       `pulumi:"source"`
	State                string                       `pulumi:"state"`
	Summary              string                       `pulumi:"summary"`
	Version              string                       `pulumi:"version"`
}

func LookupAlertOutput(ctx *pulumi.Context, args LookupAlertOutputArgs, opts ...pulumi.InvokeOption) LookupAlertResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAlertResultOutput, error) {
			args := v.(LookupAlertArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("signoz:index/getAlert:getAlert", args, LookupAlertResultOutput{}, options).(LookupAlertResultOutput), nil
		}).(LookupAlertResultOutput)
}

// A collection of arguments for invoking getAlert.
type LookupAlertOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupAlertOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlertArgs)(nil)).Elem()
}

// A collection of values returned by getAlert.
type LookupAlertResultOutput struct{ *pulumi.OutputState }

func (LookupAlertResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlertResult)(nil)).Elem()
}

func (o LookupAlertResultOutput) ToLookupAlertResultOutput() LookupAlertResultOutput {
	return o
}

func (o LookupAlertResultOutput) ToLookupAlertResultOutputWithContext(ctx context.Context) LookupAlertResultOutput {
	return o
}

func (o LookupAlertResultOutput) Alert() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Alert }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) AlertType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.AlertType }).(pulumi.StringOutput)
}

// Deprecated: This field is no longer needed and will be ignored
func (o LookupAlertResultOutput) BroadcastToAll() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAlertResult) bool { return v.BroadcastToAll }).(pulumi.BoolOutput)
}

func (o LookupAlertResultOutput) Condition() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Condition }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAlertResult) bool { return v.Disabled }).(pulumi.BoolOutput)
}

func (o LookupAlertResultOutput) EvalWindow() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.EvalWindow }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Evaluation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Evaluation }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Frequency() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Frequency }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupAlertResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupAlertResultOutput) NotificationSettings() GetAlertNotificationSettingsOutput {
	return o.ApplyT(func(v LookupAlertResult) GetAlertNotificationSettings { return v.NotificationSettings }).(GetAlertNotificationSettingsOutput)
}

func (o LookupAlertResultOutput) PreferredChannels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAlertResult) []string { return v.PreferredChannels }).(pulumi.StringArrayOutput)
}

func (o LookupAlertResultOutput) RuleType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.RuleType }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) SchemaVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.SchemaVersion }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Severity() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Severity }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Source }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Summary() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Summary }).(pulumi.StringOutput)
}

func (o LookupAlertResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAlertResultOutput{})
}
