// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDashboard(ctx *pulumi.Context, args *LookupDashboardArgs, opts ...pulumi.InvokeOption) (*LookupDashboardResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDashboardResult
	err := ctx.Invoke("signoz:index/getDashboard:getDashboard", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDashboard.
type LookupDashboardArgs struct {
	Id      string  `pulumi:"id"`
	Version *string `pulumi:"version"`
}

// A collection of values returned by getDashboard.
type LookupDashboardResult struct {
	CollapsableRowsMigrated bool     `pulumi:"collapsableRowsMigrated"`
	Description             string   `pulumi:"description"`
	Id                      string   `pulumi:"id"`
	Layout                  string   `pulumi:"layout"`
	Name                    string   `pulumi:"name"`
	PanelMap                string   `pulumi:"panelMap"`
	Source                  string   `pulumi:"source"`
	Tags                    []string `pulumi:"tags"`
	Title                   string   `pulumi:"title"`
	UploadedGrafana         bool     `pulumi:"uploadedGrafana"`
	Variables               string   `pulumi:"variables"`
	Version                 string   `pulumi:"version"`
	Widgets                 string   `pulumi:"widgets"`
}

func LookupDashboardOutput(ctx *pulumi.Context, args LookupDashboardOutputArgs, opts ...pulumi.InvokeOption) LookupDashboardResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupDashboardResultOutput, error) {
			args := v.(LookupDashboardArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("signoz:index/getDashboard:getDashboard", args, LookupDashboardResultOutput{}, options).(LookupDashboardResultOutput), nil
		}).(LookupDashboardResultOutput)
}

// A collection of arguments for invoking getDashboard.
type LookupDashboardOutputArgs struct {
	Id      pulumi.StringInput    `pulumi:"id"`
	Version pulumi.StringPtrInput `pulumi:"version"`
}

func (LookupDashboardOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDashboardArgs)(nil)).Elem()
}

// A collection of values returned by getDashboard.
type LookupDashboardResultOutput struct{ *pulumi.OutputState }

func (LookupDashboardResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDashboardResult)(nil)).Elem()
}

func (o LookupDashboardResultOutput) ToLookupDashboardResultOutput() LookupDashboardResultOutput {
	return o
}

func (o LookupDashboardResultOutput) ToLookupDashboardResultOutputWithContext(ctx context.Context) LookupDashboardResultOutput {
	return o
}

func (o LookupDashboardResultOutput) CollapsableRowsMigrated() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDashboardResult) bool { return v.CollapsableRowsMigrated }).(pulumi.BoolOutput)
}

func (o LookupDashboardResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Layout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Layout }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) PanelMap() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.PanelMap }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Source }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDashboardResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupDashboardResultOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Title }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) UploadedGrafana() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDashboardResult) bool { return v.UploadedGrafana }).(pulumi.BoolOutput)
}

func (o LookupDashboardResultOutput) Variables() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Variables }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Version }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Widgets() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Widgets }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDashboardResultOutput{})
}
