// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"errors"
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The SigNoz log-processing pipeline set. SigNoz manages log pipelines as a single versioned, ordered collection, so this is a **singleton** resource — declare at most one. Applying publishes a new pipeline-set version; destroying publishes an empty set.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal([]map[string]interface{}{
//				map[string]interface{}{
//					"orderId": 1,
//					"name":    "drop-health-checks",
//					"alias":   "drop-health-checks",
//					"enabled": true,
//					"filter": map[string]interface{}{
//						"op": "AND",
//						"items": []map[string]interface{}{
//							map[string]interface{}{
//								"key": map[string]interface{}{
//									"key": "http.target",
//								},
//								"op":    "=",
//								"value": "/healthz",
//							},
//						},
//					},
//					"config": []interface{}{},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			// Singleton: declare at most one signoz_log_pipeline per SigNoz instance.
//			// Applying publishes a new pipeline-set version; destroying clears the set.
//			_, err = signoz.NewLogPipeline(ctx, "main", &signoz.LogPipelineArgs{
//				Pipelines: pulumi.String(pulumi.String(json0)),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type LogPipeline struct {
	pulumi.CustomResourceState

	// Ordered array of pipeline definitions as JSON. Compared semantically.
	Pipelines pulumi.StringOutput `pulumi:"pipelines"`
}

// NewLogPipeline registers a new resource with the given unique name, arguments, and options.
func NewLogPipeline(ctx *pulumi.Context,
	name string, args *LogPipelineArgs, opts ...pulumi.ResourceOption) (*LogPipeline, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Pipelines == nil {
		return nil, errors.New("invalid value for required argument 'Pipelines'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LogPipeline
	err := ctx.RegisterResource("signoz:index/logPipeline:LogPipeline", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogPipeline gets an existing LogPipeline resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogPipeline(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogPipelineState, opts ...pulumi.ResourceOption) (*LogPipeline, error) {
	var resource LogPipeline
	err := ctx.ReadResource("signoz:index/logPipeline:LogPipeline", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogPipeline resources.
type logPipelineState struct {
	// Ordered array of pipeline definitions as JSON. Compared semantically.
	Pipelines *string `pulumi:"pipelines"`
}

type LogPipelineState struct {
	// Ordered array of pipeline definitions as JSON. Compared semantically.
	Pipelines pulumi.StringPtrInput
}

func (LogPipelineState) ElementType() reflect.Type {
	return reflect.TypeOf((*logPipelineState)(nil)).Elem()
}

type logPipelineArgs struct {
	// Ordered array of pipeline definitions as JSON. Compared semantically.
	Pipelines string `pulumi:"pipelines"`
}

// The set of arguments for constructing a LogPipeline resource.
type LogPipelineArgs struct {
	// Ordered array of pipeline definitions as JSON. Compared semantically.
	Pipelines pulumi.StringInput
}

func (LogPipelineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*logPipelineArgs)(nil)).Elem()
}

type LogPipelineInput interface {
	pulumi.Input

	ToLogPipelineOutput() LogPipelineOutput
	ToLogPipelineOutputWithContext(ctx context.Context) LogPipelineOutput
}

func (*LogPipeline) ElementType() reflect.Type {
	return reflect.TypeOf((**LogPipeline)(nil)).Elem()
}

func (i *LogPipeline) ToLogPipelineOutput() LogPipelineOutput {
	return i.ToLogPipelineOutputWithContext(context.Background())
}

func (i *LogPipeline) ToLogPipelineOutputWithContext(ctx context.Context) LogPipelineOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogPipelineOutput)
}

// LogPipelineArrayInput is an input type that accepts LogPipelineArray and LogPipelineArrayOutput values.
// You can construct a concrete instance of `LogPipelineArrayInput` via:
//
//	LogPipelineArray{ LogPipelineArgs{...} }
type LogPipelineArrayInput interface {
	pulumi.Input

	ToLogPipelineArrayOutput() LogPipelineArrayOutput
	ToLogPipelineArrayOutputWithContext(context.Context) LogPipelineArrayOutput
}

type LogPipelineArray []LogPipelineInput

func (LogPipelineArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogPipeline)(nil)).Elem()
}

func (i LogPipelineArray) ToLogPipelineArrayOutput() LogPipelineArrayOutput {
	return i.ToLogPipelineArrayOutputWithContext(context.Background())
}

func (i LogPipelineArray) ToLogPipelineArrayOutputWithContext(ctx context.Context) LogPipelineArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogPipelineArrayOutput)
}

// LogPipelineMapInput is an input type that accepts LogPipelineMap and LogPipelineMapOutput values.
// You can construct a concrete instance of `LogPipelineMapInput` via:
//
//	LogPipelineMap{ "key": LogPipelineArgs{...} }
type LogPipelineMapInput interface {
	pulumi.Input

	ToLogPipelineMapOutput() LogPipelineMapOutput
	ToLogPipelineMapOutputWithContext(context.Context) LogPipelineMapOutput
}

type LogPipelineMap map[string]LogPipelineInput

func (LogPipelineMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogPipeline)(nil)).Elem()
}

func (i LogPipelineMap) ToLogPipelineMapOutput() LogPipelineMapOutput {
	return i.ToLogPipelineMapOutputWithContext(context.Background())
}

func (i LogPipelineMap) ToLogPipelineMapOutputWithContext(ctx context.Context) LogPipelineMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogPipelineMapOutput)
}

type LogPipelineOutput struct{ *pulumi.OutputState }

func (LogPipelineOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LogPipeline)(nil)).Elem()
}

func (o LogPipelineOutput) ToLogPipelineOutput() LogPipelineOutput {
	return o
}

func (o LogPipelineOutput) ToLogPipelineOutputWithContext(ctx context.Context) LogPipelineOutput {
	return o
}

// Ordered array of pipeline definitions as JSON. Compared semantically.
func (o LogPipelineOutput) Pipelines() pulumi.StringOutput {
	return o.ApplyT(func(v *LogPipeline) pulumi.StringOutput { return v.Pipelines }).(pulumi.StringOutput)
}

type LogPipelineArrayOutput struct{ *pulumi.OutputState }

func (LogPipelineArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogPipeline)(nil)).Elem()
}

func (o LogPipelineArrayOutput) ToLogPipelineArrayOutput() LogPipelineArrayOutput {
	return o
}

func (o LogPipelineArrayOutput) ToLogPipelineArrayOutputWithContext(ctx context.Context) LogPipelineArrayOutput {
	return o
}

func (o LogPipelineArrayOutput) Index(i pulumi.IntInput) LogPipelineOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LogPipeline {
		return vs[0].([]*LogPipeline)[vs[1].(int)]
	}).(LogPipelineOutput)
}

type LogPipelineMapOutput struct{ *pulumi.OutputState }

func (LogPipelineMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogPipeline)(nil)).Elem()
}

func (o LogPipelineMapOutput) ToLogPipelineMapOutput() LogPipelineMapOutput {
	return o
}

func (o LogPipelineMapOutput) ToLogPipelineMapOutputWithContext(ctx context.Context) LogPipelineMapOutput {
	return o
}

func (o LogPipelineMapOutput) MapIndex(k pulumi.StringInput) LogPipelineOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LogPipeline {
		return vs[0].(map[string]*LogPipeline)[vs[1].(string)]
	}).(LogPipelineOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LogPipelineInput)(nil)).Elem(), &LogPipeline{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogPipelineArrayInput)(nil)).Elem(), LogPipelineArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogPipelineMapInput)(nil)).Elem(), LogPipelineMap{})
	pulumi.RegisterOutputType(LogPipelineOutput{})
	pulumi.RegisterOutputType(LogPipelineArrayOutput{})
	pulumi.RegisterOutputType(LogPipelineMapOutput{})
}
