// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the signoz package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// SigNoz Service Account access token, sent as the `SIGNOZ-API-KEY` header. May also be set via the `SIGNOZ_ACCESS_TOKEN` environment variable. Required for any real API call.
	AccessToken pulumi.StringPtrOutput `pulumi:"accessToken"`
	// Base URL of the SigNoz query-service API (e.g. `https://signoz.example.com`). Defaults to `http://localhost:3301`. May also be set via the `SIGNOZ_ENDPOINT` environment variable.
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.AccessToken != nil {
		args.AccessToken = pulumi.ToSecret(args.AccessToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"accessToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:signoz", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// SigNoz Service Account access token, sent as the `SIGNOZ-API-KEY` header. May also be set via the `SIGNOZ_ACCESS_TOKEN` environment variable. Required for any real API call.
	AccessToken *string `pulumi:"accessToken"`
	// Base URL of the SigNoz query-service API (e.g. `https://signoz.example.com`). Defaults to `http://localhost:3301`. May also be set via the `SIGNOZ_ENDPOINT` environment variable.
	Endpoint *string `pulumi:"endpoint"`
	// Maximum retries for transient (5xx / network) failures. Defaults to 3. May also be set via `SIGNOZ_HTTP_MAX_RETRY`.
	HttpMaxRetry *int `pulumi:"httpMaxRetry"`
	// Per-request HTTP timeout in seconds. Defaults to 35. May also be set via `SIGNOZ_HTTP_TIMEOUT`.
	HttpTimeout *int `pulumi:"httpTimeout"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// SigNoz Service Account access token, sent as the `SIGNOZ-API-KEY` header. May also be set via the `SIGNOZ_ACCESS_TOKEN` environment variable. Required for any real API call.
	AccessToken pulumi.StringPtrInput
	// Base URL of the SigNoz query-service API (e.g. `https://signoz.example.com`). Defaults to `http://localhost:3301`. May also be set via the `SIGNOZ_ENDPOINT` environment variable.
	Endpoint pulumi.StringPtrInput
	// Maximum retries for transient (5xx / network) failures. Defaults to 3. May also be set via `SIGNOZ_HTTP_MAX_RETRY`.
	HttpMaxRetry pulumi.IntPtrInput
	// Per-request HTTP timeout in seconds. Defaults to 35. May also be set via `SIGNOZ_HTTP_TIMEOUT`.
	HttpTimeout pulumi.IntPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:signoz/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// SigNoz Service Account access token, sent as the `SIGNOZ-API-KEY` header. May also be set via the `SIGNOZ_ACCESS_TOKEN` environment variable. Required for any real API call.
func (o ProviderOutput) AccessToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AccessToken }).(pulumi.StringPtrOutput)
}

// Base URL of the SigNoz query-service API (e.g. `https://signoz.example.com`). Defaults to `http://localhost:3301`. May also be set via the `SIGNOZ_ENDPOINT` environment variable.
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
