// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signoz

import (
	"context"
	"reflect"

	"errors"
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A saved SigNoz explorer view (logs or traces). The query state goes in `data` as JSON.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal(map[string]interface{}{
//				"compositeQuery": map[string]interface{}{
//					"queryType": "builder",
//					"panelType": "list",
//					"builderQueries": map[string]interface{}{
//						"A": map[string]interface{}{
//							"dataSource":        "logs",
//							"queryName":         "A",
//							"aggregateOperator": "noop",
//							"expression":        "A",
//							"disabled":          false,
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			_, err = signoz.NewSavedView(ctx, "errors", &signoz.SavedViewArgs{
//				Name:       pulumi.String("Errors (last 15m)"),
//				SourcePage: pulumi.String("logs"),
//				Data:       pulumi.String(pulumi.String(json0)),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type SavedView struct {
	pulumi.CustomResourceState

	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data pulumi.StringOutput `pulumi:"data"`
	// View name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage pulumi.StringOutput `pulumi:"sourcePage"`
}

// NewSavedView registers a new resource with the given unique name, arguments, and options.
func NewSavedView(ctx *pulumi.Context,
	name string, args *SavedViewArgs, opts ...pulumi.ResourceOption) (*SavedView, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Data == nil {
		return nil, errors.New("invalid value for required argument 'Data'")
	}
	if args.SourcePage == nil {
		return nil, errors.New("invalid value for required argument 'SourcePage'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SavedView
	err := ctx.RegisterResource("signoz:index/savedView:SavedView", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSavedView gets an existing SavedView resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSavedView(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SavedViewState, opts ...pulumi.ResourceOption) (*SavedView, error) {
	var resource SavedView
	err := ctx.ReadResource("signoz:index/savedView:SavedView", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SavedView resources.
type savedViewState struct {
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data *string `pulumi:"data"`
	// View name.
	Name *string `pulumi:"name"`
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage *string `pulumi:"sourcePage"`
}

type SavedViewState struct {
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data pulumi.StringPtrInput
	// View name.
	Name pulumi.StringPtrInput
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage pulumi.StringPtrInput
}

func (SavedViewState) ElementType() reflect.Type {
	return reflect.TypeOf((*savedViewState)(nil)).Elem()
}

type savedViewArgs struct {
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data string `pulumi:"data"`
	// View name.
	Name *string `pulumi:"name"`
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage string `pulumi:"sourcePage"`
}

// The set of arguments for constructing a SavedView resource.
type SavedViewArgs struct {
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data pulumi.StringInput
	// View name.
	Name pulumi.StringPtrInput
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage pulumi.StringInput
}

func (SavedViewArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*savedViewArgs)(nil)).Elem()
}

type SavedViewInput interface {
	pulumi.Input

	ToSavedViewOutput() SavedViewOutput
	ToSavedViewOutputWithContext(ctx context.Context) SavedViewOutput
}

func (*SavedView) ElementType() reflect.Type {
	return reflect.TypeOf((**SavedView)(nil)).Elem()
}

func (i *SavedView) ToSavedViewOutput() SavedViewOutput {
	return i.ToSavedViewOutputWithContext(context.Background())
}

func (i *SavedView) ToSavedViewOutputWithContext(ctx context.Context) SavedViewOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavedViewOutput)
}

// SavedViewArrayInput is an input type that accepts SavedViewArray and SavedViewArrayOutput values.
// You can construct a concrete instance of `SavedViewArrayInput` via:
//
//	SavedViewArray{ SavedViewArgs{...} }
type SavedViewArrayInput interface {
	pulumi.Input

	ToSavedViewArrayOutput() SavedViewArrayOutput
	ToSavedViewArrayOutputWithContext(context.Context) SavedViewArrayOutput
}

type SavedViewArray []SavedViewInput

func (SavedViewArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SavedView)(nil)).Elem()
}

func (i SavedViewArray) ToSavedViewArrayOutput() SavedViewArrayOutput {
	return i.ToSavedViewArrayOutputWithContext(context.Background())
}

func (i SavedViewArray) ToSavedViewArrayOutputWithContext(ctx context.Context) SavedViewArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavedViewArrayOutput)
}

// SavedViewMapInput is an input type that accepts SavedViewMap and SavedViewMapOutput values.
// You can construct a concrete instance of `SavedViewMapInput` via:
//
//	SavedViewMap{ "key": SavedViewArgs{...} }
type SavedViewMapInput interface {
	pulumi.Input

	ToSavedViewMapOutput() SavedViewMapOutput
	ToSavedViewMapOutputWithContext(context.Context) SavedViewMapOutput
}

type SavedViewMap map[string]SavedViewInput

func (SavedViewMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SavedView)(nil)).Elem()
}

func (i SavedViewMap) ToSavedViewMapOutput() SavedViewMapOutput {
	return i.ToSavedViewMapOutputWithContext(context.Background())
}

func (i SavedViewMap) ToSavedViewMapOutputWithContext(ctx context.Context) SavedViewMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavedViewMapOutput)
}

type SavedViewOutput struct{ *pulumi.OutputState }

func (SavedViewOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SavedView)(nil)).Elem()
}

func (o SavedViewOutput) ToSavedViewOutput() SavedViewOutput {
	return o
}

func (o SavedViewOutput) ToSavedViewOutputWithContext(ctx context.Context) SavedViewOutput {
	return o
}

// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
func (o SavedViewOutput) Data() pulumi.StringOutput {
	return o.ApplyT(func(v *SavedView) pulumi.StringOutput { return v.Data }).(pulumi.StringOutput)
}

// View name.
func (o SavedViewOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SavedView) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Explorer the view belongs to: `logs` or `traces`.
func (o SavedViewOutput) SourcePage() pulumi.StringOutput {
	return o.ApplyT(func(v *SavedView) pulumi.StringOutput { return v.SourcePage }).(pulumi.StringOutput)
}

type SavedViewArrayOutput struct{ *pulumi.OutputState }

func (SavedViewArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SavedView)(nil)).Elem()
}

func (o SavedViewArrayOutput) ToSavedViewArrayOutput() SavedViewArrayOutput {
	return o
}

func (o SavedViewArrayOutput) ToSavedViewArrayOutputWithContext(ctx context.Context) SavedViewArrayOutput {
	return o
}

func (o SavedViewArrayOutput) Index(i pulumi.IntInput) SavedViewOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SavedView {
		return vs[0].([]*SavedView)[vs[1].(int)]
	}).(SavedViewOutput)
}

type SavedViewMapOutput struct{ *pulumi.OutputState }

func (SavedViewMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SavedView)(nil)).Elem()
}

func (o SavedViewMapOutput) ToSavedViewMapOutput() SavedViewMapOutput {
	return o
}

func (o SavedViewMapOutput) ToSavedViewMapOutputWithContext(ctx context.Context) SavedViewMapOutput {
	return o
}

func (o SavedViewMapOutput) MapIndex(k pulumi.StringInput) SavedViewOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SavedView {
		return vs[0].(map[string]*SavedView)[vs[1].(string)]
	}).(SavedViewOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SavedViewInput)(nil)).Elem(), &SavedView{})
	pulumi.RegisterInputType(reflect.TypeOf((*SavedViewArrayInput)(nil)).Elem(), SavedViewArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SavedViewMapInput)(nil)).Elem(), SavedViewMap{})
	pulumi.RegisterOutputType(SavedViewOutput{})
	pulumi.RegisterOutputType(SavedViewArrayOutput{})
	pulumi.RegisterOutputType(SavedViewMapOutput{})
}
