// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// SigNoz Service Account access token, sent as the `SIGNOZ-API-KEY` header. May also be set via the `SIGNOZ_ACCESS_TOKEN` environment variable. Required for any real API call.
func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "signoz:accessToken")
}

// Base URL of the SigNoz query-service API (e.g. `https://signoz.example.com`). Defaults to `http://localhost:3301`. May also be set via the `SIGNOZ_ENDPOINT` environment variable.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "signoz:endpoint")
}

// Maximum retries for transient (5xx / network) failures. Defaults to 3. May also be set via `SIGNOZ_HTTP_MAX_RETRY`.
func GetHttpMaxRetry(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "signoz:httpMaxRetry")
}

// Per-request HTTP timeout in seconds. Defaults to 35. May also be set via `SIGNOZ_HTTP_TIMEOUT`.
func GetHttpTimeout(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "signoz:httpTimeout")
}
