// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/jgautheron/pulumi-signoz/sdk/go/signoz/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Access token of the SigNoz API. You can retrieve it from SigNoz UI
// with Admin Role ([documentation](https://signoz.io/newsroom/launch-week-1-day-5/#using-access-token)).
// Also, you can set it using environment variable SIGNOZ_ACCESS_TOKEN.
func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "signoz:accessToken")
}

// Endpoint of the SigNoz. It is the root URL of the SigNoz UI.
// Also, you can set it using environment variable SIGNOZ_ENDPOINT. If not set, it defaults to http://localhost:3301.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "signoz:endpoint")
}

// Specifies the max retry limit for the HTTP requests made to SigNoz.
// Also, you can set it using environment variable SIGNOZ_HTTP_MAX_RETRY. If not set, it defaults to 10.
func GetHttpMaxRetry(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "signoz:httpMaxRetry")
}

// Specifies the timeout limit in seconds for the HTTP requests made to SigNoz.
// Also, you can set it using environment variable SIGNOZ_HTTP_TIMEOUT. If not set, it defaults to 35.
func GetHttpTimeout(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "signoz:httpTimeout")
}
