// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JGautheron.Pulumi.Signoz.Inputs
{

    public sealed class AlertNotificationSettingsRenotifyArgs : global::Pulumi.ResourceArgs
    {
        [Input("alertStates", required: true)]
        private InputList<string>? _alertStates;

        /// <summary>
        /// For which AlertStates of the alert want to get renotified.
        /// </summary>
        public InputList<string> AlertStates
        {
            get => _alertStates ?? (_alertStates = new InputList<string>());
            set => _alertStates = value;
        }

        /// <summary>
        /// To enable the re-notification of the alert.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Re-notify interval of the alert.
        /// </summary>
        [Input("interval", required: true)]
        public Input<string> Interval { get; set; } = null!;

        public AlertNotificationSettingsRenotifyArgs()
        {
        }
        public static new AlertNotificationSettingsRenotifyArgs Empty => new AlertNotificationSettingsRenotifyArgs();
    }
}
