// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jooon.Pulumi.Signoz
{
    [SignozResourceType("signoz:index/alert:Alert")]
    public partial class Alert : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the alert.
        /// </summary>
        [Output("alert")]
        public Output<string> AlertConfig { get; private set; } = null!;

        /// <summary>
        /// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
        /// </summary>
        [Output("alertType")]
        public Output<string> AlertType { get; private set; } = null!;

        /// <summary>
        /// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
        /// </summary>
        [Output("broadcastToAll")]
        public Output<bool> BroadcastToAll { get; private set; } = null!;

        /// <summary>
        /// Condition of the alert.
        /// </summary>
        [Output("condition")]
        public Output<string> Condition { get; private set; } = null!;

        /// <summary>
        /// Creation time of the alert.
        /// </summary>
        [Output("createAt")]
        public Output<string> CreateAt { get; private set; } = null!;

        /// <summary>
        /// Creator of the alert.
        /// </summary>
        [Output("createBy")]
        public Output<string> CreateBy { get; private set; } = null!;

        /// <summary>
        /// Description of the alert.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Whether the alert is disabled.
        /// </summary>
        [Output("disabled")]
        public Output<bool> Disabled { get; private set; } = null!;

        /// <summary>
        /// The evaluation window of the alert. By default, it is 5m0s.
        /// </summary>
        [Output("evalWindow")]
        public Output<string> EvalWindow { get; private set; } = null!;

        /// <summary>
        /// Evaluation settings for the alert (JSON). Only used when SchemaVersion is v2 or higher.
        /// </summary>
        [Output("evaluation")]
        public Output<string> Evaluation { get; private set; } = null!;

        /// <summary>
        /// The frequency of the alert. By default, it is 1m0s.
        /// </summary>
        [Output("frequency")]
        public Output<string> Frequency { get; private set; } = null!;

        /// <summary>
        /// Labels of the alert. Severity is a required label.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>> Labels { get; private set; } = null!;

        /// <summary>
        /// Notification settings for the alert. Only used when SchemaVersion is v2 or higher.
        /// </summary>
        [Output("notificationSettings")]
        public Output<Outputs.AlertNotificationSettings> NotificationSettings { get; private set; } = null!;

        /// <summary>
        /// Preferred channels of the alert. By default, it is empty.
        /// </summary>
        [Output("preferredChannels")]
        public Output<ImmutableArray<string>> PreferredChannels { get; private set; } = null!;

        /// <summary>
        /// Type of the alert. Possible values are: ThresholdRule and promql_rule.
        /// </summary>
        [Output("ruleType")]
        public Output<string> RuleType { get; private set; } = null!;

        /// <summary>
        /// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and NotificationSettings are supported.
        /// </summary>
        [Output("schemaVersion")]
        public Output<string> SchemaVersion { get; private set; } = null!;

        /// <summary>
        /// Severity of the alert. Possible values are: info, warning, error, and critical.
        /// </summary>
        [Output("severity")]
        public Output<string> Severity { get; private set; } = null!;

        /// <summary>
        /// Source of the alert. By default, it is &lt;SIGNOZ_ENDPOINT&gt;/alerts.
        /// </summary>
        [Output("source")]
        public Output<string> Source { get; private set; } = null!;

        /// <summary>
        /// State of the alert.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// Summary of the alert.
        /// </summary>
        [Output("summary")]
        public Output<string> Summary { get; private set; } = null!;

        /// <summary>
        /// Last update time of the alert.
        /// </summary>
        [Output("updateAt")]
        public Output<string> UpdateAt { get; private set; } = null!;

        /// <summary>
        /// Last updater of the alert.
        /// </summary>
        [Output("updateBy")]
        public Output<string> UpdateBy { get; private set; } = null!;

        /// <summary>
        /// Version of the alert. By default, it is v4.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Alert resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Alert(string name, AlertArgs args, CustomResourceOptions? options = null)
            : base("signoz:index/alert:Alert", name, args ?? new AlertArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Alert(string name, Input<string> id, AlertState? state = null, CustomResourceOptions? options = null)
            : base("signoz:index/alert:Alert", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Alert resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Alert Get(string name, Input<string> id, AlertState? state = null, CustomResourceOptions? options = null)
        {
            return new Alert(name, id, state, options);
        }
    }

    public sealed class AlertArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the alert.
        /// </summary>
        [Input("alert", required: true)]
        public Input<string> AlertConfig { get; set; } = null!;

        /// <summary>
        /// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
        /// </summary>
        [Input("alertType", required: true)]
        public Input<string> AlertType { get; set; } = null!;

        /// <summary>
        /// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
        /// </summary>
        [Input("broadcastToAll")]
        public Input<bool>? BroadcastToAll { get; set; }

        /// <summary>
        /// Condition of the alert.
        /// </summary>
        [Input("condition", required: true)]
        public Input<string> Condition { get; set; } = null!;

        /// <summary>
        /// Description of the alert.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the alert is disabled.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The evaluation window of the alert. By default, it is 5m0s.
        /// </summary>
        [Input("evalWindow")]
        public Input<string>? EvalWindow { get; set; }

        /// <summary>
        /// Evaluation settings for the alert (JSON). Only used when SchemaVersion is v2 or higher.
        /// </summary>
        [Input("evaluation")]
        public Input<string>? Evaluation { get; set; }

        /// <summary>
        /// The frequency of the alert. By default, it is 1m0s.
        /// </summary>
        [Input("frequency")]
        public Input<string>? Frequency { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Labels of the alert. Severity is a required label.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Notification settings for the alert. Only used when SchemaVersion is v2 or higher.
        /// </summary>
        [Input("notificationSettings")]
        public Input<Inputs.AlertNotificationSettingsArgs>? NotificationSettings { get; set; }

        [Input("preferredChannels")]
        private InputList<string>? _preferredChannels;

        /// <summary>
        /// Preferred channels of the alert. By default, it is empty.
        /// </summary>
        public InputList<string> PreferredChannels
        {
            get => _preferredChannels ?? (_preferredChannels = new InputList<string>());
            set => _preferredChannels = value;
        }

        /// <summary>
        /// Type of the alert. Possible values are: ThresholdRule and promql_rule.
        /// </summary>
        [Input("ruleType")]
        public Input<string>? RuleType { get; set; }

        /// <summary>
        /// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and NotificationSettings are supported.
        /// </summary>
        [Input("schemaVersion")]
        public Input<string>? SchemaVersion { get; set; }

        /// <summary>
        /// Severity of the alert. Possible values are: info, warning, error, and critical.
        /// </summary>
        [Input("severity", required: true)]
        public Input<string> Severity { get; set; } = null!;

        /// <summary>
        /// Source of the alert. By default, it is &lt;SIGNOZ_ENDPOINT&gt;/alerts.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        /// <summary>
        /// Summary of the alert.
        /// </summary>
        [Input("summary")]
        public Input<string>? Summary { get; set; }

        /// <summary>
        /// Version of the alert. By default, it is v4.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public AlertArgs()
        {
        }
        public static new AlertArgs Empty => new AlertArgs();
    }

    public sealed class AlertState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the alert.
        /// </summary>
        [Input("alert")]
        public Input<string>? AlertConfig { get; set; }

        /// <summary>
        /// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
        /// </summary>
        [Input("alertType")]
        public Input<string>? AlertType { get; set; }

        /// <summary>
        /// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
        /// </summary>
        [Input("broadcastToAll")]
        public Input<bool>? BroadcastToAll { get; set; }

        /// <summary>
        /// Condition of the alert.
        /// </summary>
        [Input("condition")]
        public Input<string>? Condition { get; set; }

        /// <summary>
        /// Creation time of the alert.
        /// </summary>
        [Input("createAt")]
        public Input<string>? CreateAt { get; set; }

        /// <summary>
        /// Creator of the alert.
        /// </summary>
        [Input("createBy")]
        public Input<string>? CreateBy { get; set; }

        /// <summary>
        /// Description of the alert.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the alert is disabled.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The evaluation window of the alert. By default, it is 5m0s.
        /// </summary>
        [Input("evalWindow")]
        public Input<string>? EvalWindow { get; set; }

        /// <summary>
        /// Evaluation settings for the alert (JSON). Only used when SchemaVersion is v2 or higher.
        /// </summary>
        [Input("evaluation")]
        public Input<string>? Evaluation { get; set; }

        /// <summary>
        /// The frequency of the alert. By default, it is 1m0s.
        /// </summary>
        [Input("frequency")]
        public Input<string>? Frequency { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Labels of the alert. Severity is a required label.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Notification settings for the alert. Only used when SchemaVersion is v2 or higher.
        /// </summary>
        [Input("notificationSettings")]
        public Input<Inputs.AlertNotificationSettingsGetArgs>? NotificationSettings { get; set; }

        [Input("preferredChannels")]
        private InputList<string>? _preferredChannels;

        /// <summary>
        /// Preferred channels of the alert. By default, it is empty.
        /// </summary>
        public InputList<string> PreferredChannels
        {
            get => _preferredChannels ?? (_preferredChannels = new InputList<string>());
            set => _preferredChannels = value;
        }

        /// <summary>
        /// Type of the alert. Possible values are: ThresholdRule and promql_rule.
        /// </summary>
        [Input("ruleType")]
        public Input<string>? RuleType { get; set; }

        /// <summary>
        /// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and NotificationSettings are supported.
        /// </summary>
        [Input("schemaVersion")]
        public Input<string>? SchemaVersion { get; set; }

        /// <summary>
        /// Severity of the alert. Possible values are: info, warning, error, and critical.
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// Source of the alert. By default, it is &lt;SIGNOZ_ENDPOINT&gt;/alerts.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        /// <summary>
        /// State of the alert.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// Summary of the alert.
        /// </summary>
        [Input("summary")]
        public Input<string>? Summary { get; set; }

        /// <summary>
        /// Last update time of the alert.
        /// </summary>
        [Input("updateAt")]
        public Input<string>? UpdateAt { get; set; }

        /// <summary>
        /// Last updater of the alert.
        /// </summary>
        [Input("updateBy")]
        public Input<string>? UpdateBy { get; set; }

        /// <summary>
        /// Version of the alert. By default, it is v4.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public AlertState()
        {
        }
        public static new AlertState Empty => new AlertState();
    }
}
