// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jooon.Pulumi.Signoz
{
    /// <summary>
    /// A SigNoz alert rule. Top-level fields are typed; the query `Condition`, `Evaluation`, and `NotificationSettings` are JSON blobs (export from the SigNoz UI to adapt). Defaults target the v5 / v2alpha1 schema required by SigNoz &gt;= 0.125.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Signoz = Jooon.Pulumi.Signoz;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // A logs-based alert on the v5 / v2alpha1 schema (SigNoz &gt;= 0.125).
    ///     // The threshold references a notification channel by name.
    ///     var highErrorLogs = new Signoz.Alert("high_error_logs", new()
    ///     {
    ///         AlertConfig = "High error log volume",
    ///         AlertType = "LOGS_BASED_ALERT",
    ///         Severity = "warning",
    ///         Condition = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["compositeQuery"] = new Dictionary&lt;string, object?&gt;
    ///             {
    ///                 ["queryType"] = "builder",
    ///                 ["panelType"] = "graph",
    ///                 ["queries"] = new[]
    ///                 {
    ///                     new Dictionary&lt;string, object?&gt;
    ///                     {
    ///                         ["type"] = "builder_query",
    ///                         ["spec"] = new Dictionary&lt;string, object?&gt;
    ///                         {
    ///                             ["name"] = "A",
    ///                             ["signal"] = "logs",
    ///                             ["stepInterval"] = 0,
    ///                             ["aggregations"] = new[]
    ///                             {
    ///                                 new Dictionary&lt;string, object?&gt;
    ///                                 {
    ///                                     ["expression"] = "count()",
    ///                                 },
    ///                             },
    ///                             ["filter"] = new Dictionary&lt;string, object?&gt;
    ///                             {
    ///                                 ["expression"] = "severity_text = 'ERROR'",
    ///                             },
    ///                             ["having"] = new Dictionary&lt;string, object?&gt;
    ///                             {
    ///                                 ["expression"] = "",
    ///                             },
    ///                         },
    ///                     },
    ///                 },
    ///             },
    ///             ["selectedQueryName"] = "A",
    ///             ["thresholds"] = new Dictionary&lt;string, object?&gt;
    ///             {
    ///                 ["kind"] = "basic",
    ///                 ["spec"] = new[]
    ///                 {
    ///                     new Dictionary&lt;string, object?&gt;
    ///                     {
    ///                         ["name"] = "warning",
    ///                         ["target"] = 100,
    ///                         ["matchType"] = "1",
    ///                         ["op"] = "1",
    ///                         ["channels"] = new[]
    ///                         {
    ///                             slack.Name,
    ///                         },
    ///                     },
    ///                 },
    ///             },
    ///         }),
    ///         Evaluation = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["kind"] = "rolling",
    ///             ["spec"] = new Dictionary&lt;string, object?&gt;
    ///             {
    ///                 ["evalWindow"] = "5m0s",
    ///                 ["frequency"] = "1m0s",
    ///             },
    ///         }),
    ///         PreferredChannels = new[]
    ///         {
    ///             slack.Name,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SignozResourceType("signoz:index/alert:Alert")]
    public partial class Alert : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Alert name.
        /// </summary>
        [Output("alert")]
        public Output<string> AlertConfig { get; private set; } = null!;

        /// <summary>
        /// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        /// </summary>
        [Output("alertType")]
        public Output<string> AlertType { get; private set; } = null!;

        /// <summary>
        /// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        /// </summary>
        [Output("condition")]
        public Output<string> Condition { get; private set; } = null!;

        /// <summary>
        /// Human-readable description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Whether the rule is disabled. Defaults to false.
        /// </summary>
        [Output("disabled")]
        public Output<bool> Disabled { get; private set; } = null!;

        /// <summary>
        /// Evaluation window (e.g. `5m0s`).
        /// </summary>
        [Output("evalWindow")]
        public Output<string> EvalWindow { get; private set; } = null!;

        /// <summary>
        /// Evaluation block as JSON (v2alpha1+). Compared semantically.
        /// </summary>
        [Output("evaluation")]
        public Output<string?> Evaluation { get; private set; } = null!;

        /// <summary>
        /// Evaluation frequency (e.g. `1m0s`).
        /// </summary>
        [Output("frequency")]
        public Output<string> Frequency { get; private set; } = null!;

        /// <summary>
        /// Custom labels attached to the alert.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        /// </summary>
        [Output("notificationSettings")]
        public Output<string?> NotificationSettings { get; private set; } = null!;

        /// <summary>
        /// Notification channel names the alert routes to.
        /// </summary>
        [Output("preferredChannels")]
        public Output<ImmutableArray<string>> PreferredChannels { get; private set; } = null!;

        /// <summary>
        /// Rule engine type: `ThresholdRule` (default) or `PromqlRule`.
        /// </summary>
        [Output("ruleType")]
        public Output<string> RuleType { get; private set; } = null!;

        /// <summary>
        /// Alert schema version. Defaults to `V2alpha1`.
        /// </summary>
        [Output("schemaVersion")]
        public Output<string> SchemaVersion { get; private set; } = null!;

        /// <summary>
        /// Severity label (e.g. `Info`, `Warning`, `Critical`).
        /// </summary>
        [Output("severity")]
        public Output<string?> Severity { get; private set; } = null!;

        /// <summary>
        /// Source URL recorded on the rule.
        /// </summary>
        [Output("source")]
        public Output<string?> Source { get; private set; } = null!;

        /// <summary>
        /// Alert API version. Defaults to `V5` (required by SigNoz &gt;= 0.125).
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Alert resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Alert(string name, AlertArgs args, CustomResourceOptions? options = null)
            : base("signoz:index/alert:Alert", name, args ?? new AlertArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Alert(string name, Input<string> id, AlertState? state = null, CustomResourceOptions? options = null)
            : base("signoz:index/alert:Alert", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Alert resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Alert Get(string name, Input<string> id, AlertState? state = null, CustomResourceOptions? options = null)
        {
            return new Alert(name, id, state, options);
        }
    }

    public sealed class AlertArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Alert name.
        /// </summary>
        [Input("alert", required: true)]
        public Input<string> AlertConfig { get; set; } = null!;

        /// <summary>
        /// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        /// </summary>
        [Input("alertType", required: true)]
        public Input<string> AlertType { get; set; } = null!;

        /// <summary>
        /// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        /// </summary>
        [Input("condition", required: true)]
        public Input<string> Condition { get; set; } = null!;

        /// <summary>
        /// Human-readable description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the rule is disabled. Defaults to false.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// Evaluation window (e.g. `5m0s`).
        /// </summary>
        [Input("evalWindow")]
        public Input<string>? EvalWindow { get; set; }

        /// <summary>
        /// Evaluation block as JSON (v2alpha1+). Compared semantically.
        /// </summary>
        [Input("evaluation")]
        public Input<string>? Evaluation { get; set; }

        /// <summary>
        /// Evaluation frequency (e.g. `1m0s`).
        /// </summary>
        [Input("frequency")]
        public Input<string>? Frequency { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Custom labels attached to the alert.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        /// </summary>
        [Input("notificationSettings")]
        public Input<string>? NotificationSettings { get; set; }

        [Input("preferredChannels")]
        private InputList<string>? _preferredChannels;

        /// <summary>
        /// Notification channel names the alert routes to.
        /// </summary>
        public InputList<string> PreferredChannels
        {
            get => _preferredChannels ?? (_preferredChannels = new InputList<string>());
            set => _preferredChannels = value;
        }

        /// <summary>
        /// Rule engine type: `ThresholdRule` (default) or `PromqlRule`.
        /// </summary>
        [Input("ruleType")]
        public Input<string>? RuleType { get; set; }

        /// <summary>
        /// Alert schema version. Defaults to `V2alpha1`.
        /// </summary>
        [Input("schemaVersion")]
        public Input<string>? SchemaVersion { get; set; }

        /// <summary>
        /// Severity label (e.g. `Info`, `Warning`, `Critical`).
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// Source URL recorded on the rule.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        /// <summary>
        /// Alert API version. Defaults to `V5` (required by SigNoz &gt;= 0.125).
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public AlertArgs()
        {
        }
        public static new AlertArgs Empty => new AlertArgs();
    }

    public sealed class AlertState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Alert name.
        /// </summary>
        [Input("alert")]
        public Input<string>? AlertConfig { get; set; }

        /// <summary>
        /// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
        /// </summary>
        [Input("alertType")]
        public Input<string>? AlertType { get; set; }

        /// <summary>
        /// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
        /// </summary>
        [Input("condition")]
        public Input<string>? Condition { get; set; }

        /// <summary>
        /// Human-readable description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the rule is disabled. Defaults to false.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// Evaluation window (e.g. `5m0s`).
        /// </summary>
        [Input("evalWindow")]
        public Input<string>? EvalWindow { get; set; }

        /// <summary>
        /// Evaluation block as JSON (v2alpha1+). Compared semantically.
        /// </summary>
        [Input("evaluation")]
        public Input<string>? Evaluation { get; set; }

        /// <summary>
        /// Evaluation frequency (e.g. `1m0s`).
        /// </summary>
        [Input("frequency")]
        public Input<string>? Frequency { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Custom labels attached to the alert.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
        /// </summary>
        [Input("notificationSettings")]
        public Input<string>? NotificationSettings { get; set; }

        [Input("preferredChannels")]
        private InputList<string>? _preferredChannels;

        /// <summary>
        /// Notification channel names the alert routes to.
        /// </summary>
        public InputList<string> PreferredChannels
        {
            get => _preferredChannels ?? (_preferredChannels = new InputList<string>());
            set => _preferredChannels = value;
        }

        /// <summary>
        /// Rule engine type: `ThresholdRule` (default) or `PromqlRule`.
        /// </summary>
        [Input("ruleType")]
        public Input<string>? RuleType { get; set; }

        /// <summary>
        /// Alert schema version. Defaults to `V2alpha1`.
        /// </summary>
        [Input("schemaVersion")]
        public Input<string>? SchemaVersion { get; set; }

        /// <summary>
        /// Severity label (e.g. `Info`, `Warning`, `Critical`).
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// Source URL recorded on the rule.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        /// <summary>
        /// Alert API version. Defaults to `V5` (required by SigNoz &gt;= 0.125).
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public AlertState()
        {
        }
        public static new AlertState Empty => new AlertState();
    }
}
