// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JGautheron.Pulumi.Signoz
{
    [SignozResourceType("signoz:index/dashboard:Dashboard")]
    public partial class Dashboard : global::Pulumi.CustomResource
    {
        [Output("collapsableRowsMigrated")]
        public Output<bool> CollapsableRowsMigrated { get; private set; } = null!;

        /// <summary>
        /// Creation time of the dashboard.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Creator of the dashboard.
        /// </summary>
        [Output("createdBy")]
        public Output<string> CreatedBy { get; private set; } = null!;

        /// <summary>
        /// Description of the dashboard.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Layout of the dashboard.
        /// </summary>
        [Output("layout")]
        public Output<string> Layout { get; private set; } = null!;

        /// <summary>
        /// Name of the dashboard.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("panelMap")]
        public Output<string?> PanelMap { get; private set; } = null!;

        /// <summary>
        /// Source of the dashboard. By default, it is &lt;SIGNOZ_ENDPOINT&gt;/dashboard.
        /// </summary>
        [Output("source")]
        public Output<string> Source { get; private set; } = null!;

        /// <summary>
        /// Tags of the dashboard.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Title of the dashboard.
        /// </summary>
        [Output("title")]
        public Output<string> Title { get; private set; } = null!;

        /// <summary>
        /// Last update time of the dashboard.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Last updater of the dashboard.
        /// </summary>
        [Output("updatedBy")]
        public Output<string> UpdatedBy { get; private set; } = null!;

        [Output("uploadedGrafana")]
        public Output<bool> UploadedGrafana { get; private set; } = null!;

        /// <summary>
        /// Variables for the dashboard.
        /// </summary>
        [Output("variables")]
        public Output<string> Variables { get; private set; } = null!;

        /// <summary>
        /// Version of the dashboard.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;

        /// <summary>
        /// Widgets for the dashboard.
        /// </summary>
        [Output("widgets")]
        public Output<string> Widgets { get; private set; } = null!;


        /// <summary>
        /// Create a Dashboard resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Dashboard(string name, DashboardArgs args, CustomResourceOptions? options = null)
            : base("signoz:index/dashboard:Dashboard", name, args ?? new DashboardArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Dashboard(string name, Input<string> id, DashboardState? state = null, CustomResourceOptions? options = null)
            : base("signoz:index/dashboard:Dashboard", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Dashboard resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Dashboard Get(string name, Input<string> id, DashboardState? state = null, CustomResourceOptions? options = null)
        {
            return new Dashboard(name, id, state, options);
        }
    }

    public sealed class DashboardArgs : global::Pulumi.ResourceArgs
    {
        [Input("collapsableRowsMigrated", required: true)]
        public Input<bool> CollapsableRowsMigrated { get; set; } = null!;

        /// <summary>
        /// Description of the dashboard.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Layout of the dashboard.
        /// </summary>
        [Input("layout", required: true)]
        public Input<string> Layout { get; set; } = null!;

        /// <summary>
        /// Name of the dashboard.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("panelMap")]
        public Input<string>? PanelMap { get; set; }

        /// <summary>
        /// Source of the dashboard. By default, it is &lt;SIGNOZ_ENDPOINT&gt;/dashboard.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags of the dashboard.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Title of the dashboard.
        /// </summary>
        [Input("title", required: true)]
        public Input<string> Title { get; set; } = null!;

        [Input("uploadedGrafana", required: true)]
        public Input<bool> UploadedGrafana { get; set; } = null!;

        /// <summary>
        /// Variables for the dashboard.
        /// </summary>
        [Input("variables", required: true)]
        public Input<string> Variables { get; set; } = null!;

        /// <summary>
        /// Version of the dashboard.
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        /// <summary>
        /// Widgets for the dashboard.
        /// </summary>
        [Input("widgets", required: true)]
        public Input<string> Widgets { get; set; } = null!;

        public DashboardArgs()
        {
        }
        public static new DashboardArgs Empty => new DashboardArgs();
    }

    public sealed class DashboardState : global::Pulumi.ResourceArgs
    {
        [Input("collapsableRowsMigrated")]
        public Input<bool>? CollapsableRowsMigrated { get; set; }

        /// <summary>
        /// Creation time of the dashboard.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Creator of the dashboard.
        /// </summary>
        [Input("createdBy")]
        public Input<string>? CreatedBy { get; set; }

        /// <summary>
        /// Description of the dashboard.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Layout of the dashboard.
        /// </summary>
        [Input("layout")]
        public Input<string>? Layout { get; set; }

        /// <summary>
        /// Name of the dashboard.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("panelMap")]
        public Input<string>? PanelMap { get; set; }

        /// <summary>
        /// Source of the dashboard. By default, it is &lt;SIGNOZ_ENDPOINT&gt;/dashboard.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags of the dashboard.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Title of the dashboard.
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// Last update time of the dashboard.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Last updater of the dashboard.
        /// </summary>
        [Input("updatedBy")]
        public Input<string>? UpdatedBy { get; set; }

        [Input("uploadedGrafana")]
        public Input<bool>? UploadedGrafana { get; set; }

        /// <summary>
        /// Variables for the dashboard.
        /// </summary>
        [Input("variables")]
        public Input<string>? Variables { get; set; }

        /// <summary>
        /// Version of the dashboard.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        /// <summary>
        /// Widgets for the dashboard.
        /// </summary>
        [Input("widgets")]
        public Input<string>? Widgets { get; set; }

        public DashboardState()
        {
        }
        public static new DashboardState Empty => new DashboardState();
    }
}
