// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JGautheron.Pulumi.Signoz
{
    public static class GetAlert
    {
        public static Task<GetAlertResult> InvokeAsync(GetAlertArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAlertResult>("signoz:index/getAlert:getAlert", args ?? new GetAlertArgs(), options.WithDefaults());

        public static Output<GetAlertResult> Invoke(GetAlertInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlertResult>("signoz:index/getAlert:getAlert", args ?? new GetAlertInvokeArgs(), options.WithDefaults());

        public static Output<GetAlertResult> Invoke(GetAlertInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlertResult>("signoz:index/getAlert:getAlert", args ?? new GetAlertInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAlertArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetAlertArgs()
        {
        }
        public static new GetAlertArgs Empty => new GetAlertArgs();
    }

    public sealed class GetAlertInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetAlertInvokeArgs()
        {
        }
        public static new GetAlertInvokeArgs Empty => new GetAlertInvokeArgs();
    }


    [OutputType]
    public sealed class GetAlertResult
    {
        public readonly string AlertConfig;
        public readonly string AlertType;
        public readonly bool BroadcastToAll;
        public readonly string Condition;
        public readonly string Description;
        public readonly bool Disabled;
        public readonly string EvalWindow;
        public readonly string Evaluation;
        public readonly string Frequency;
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly Outputs.GetAlertNotificationSettingsResult NotificationSettings;
        public readonly ImmutableArray<string> PreferredChannels;
        public readonly string RuleType;
        public readonly string SchemaVersion;
        public readonly string Severity;
        public readonly string Source;
        public readonly string State;
        public readonly string Summary;
        public readonly string Version;

        [OutputConstructor]
        private GetAlertResult(
            string alert,

            string alertType,

            bool broadcastToAll,

            string condition,

            string description,

            bool disabled,

            string evalWindow,

            string evaluation,

            string frequency,

            string id,

            ImmutableDictionary<string, string> labels,

            Outputs.GetAlertNotificationSettingsResult notificationSettings,

            ImmutableArray<string> preferredChannels,

            string ruleType,

            string schemaVersion,

            string severity,

            string source,

            string state,

            string summary,

            string version)
        {
            AlertConfig = alert;
            AlertType = alertType;
            BroadcastToAll = broadcastToAll;
            Condition = condition;
            Description = description;
            Disabled = disabled;
            EvalWindow = evalWindow;
            Evaluation = evaluation;
            Frequency = frequency;
            Id = id;
            Labels = labels;
            NotificationSettings = notificationSettings;
            PreferredChannels = preferredChannels;
            RuleType = ruleType;
            SchemaVersion = schemaVersion;
            Severity = severity;
            Source = source;
            State = state;
            Summary = summary;
            Version = version;
        }
    }
}
