// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jooon.Pulumi.Signoz
{
    public static class GetDashboard
    {
        public static Task<GetDashboardResult> InvokeAsync(GetDashboardArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDashboardResult>("signoz:index/getDashboard:getDashboard", args ?? new GetDashboardArgs(), options.WithDefaults());

        public static Output<GetDashboardResult> Invoke(GetDashboardInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDashboardResult>("signoz:index/getDashboard:getDashboard", args ?? new GetDashboardInvokeArgs(), options.WithDefaults());

        public static Output<GetDashboardResult> Invoke(GetDashboardInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDashboardResult>("signoz:index/getDashboard:getDashboard", args ?? new GetDashboardInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDashboardArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("version")]
        public string? Version { get; set; }

        public GetDashboardArgs()
        {
        }
        public static new GetDashboardArgs Empty => new GetDashboardArgs();
    }

    public sealed class GetDashboardInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("version")]
        public Input<string>? Version { get; set; }

        public GetDashboardInvokeArgs()
        {
        }
        public static new GetDashboardInvokeArgs Empty => new GetDashboardInvokeArgs();
    }


    [OutputType]
    public sealed class GetDashboardResult
    {
        public readonly bool CollapsableRowsMigrated;
        public readonly string Description;
        public readonly string Id;
        public readonly string Layout;
        public readonly string Name;
        public readonly string PanelMap;
        public readonly string Source;
        public readonly ImmutableArray<string> Tags;
        public readonly string Title;
        public readonly bool UploadedGrafana;
        public readonly string Variables;
        public readonly string Version;
        public readonly string Widgets;

        [OutputConstructor]
        private GetDashboardResult(
            bool collapsableRowsMigrated,

            string description,

            string id,

            string layout,

            string name,

            string panelMap,

            string source,

            ImmutableArray<string> tags,

            string title,

            bool uploadedGrafana,

            string variables,

            string version,

            string widgets)
        {
            CollapsableRowsMigrated = collapsableRowsMigrated;
            Description = description;
            Id = id;
            Layout = layout;
            Name = name;
            PanelMap = panelMap;
            Source = source;
            Tags = tags;
            Title = title;
            UploadedGrafana = uploadedGrafana;
            Variables = variables;
            Version = version;
            Widgets = widgets;
        }
    }
}
