// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jooon.Pulumi.Signoz
{
    /// <summary>
    /// A saved SigNoz explorer view (logs or traces). The query state goes in `Data` as JSON.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Signoz = Jooon.Pulumi.Signoz;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var errors = new Signoz.SavedView("errors", new()
    ///     {
    ///         Name = "Errors (last 15m)",
    ///         SourcePage = "logs",
    ///         Data = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["compositeQuery"] = new Dictionary&lt;string, object?&gt;
    ///             {
    ///                 ["queryType"] = "builder",
    ///                 ["panelType"] = "list",
    ///                 ["builderQueries"] = new Dictionary&lt;string, object?&gt;
    ///                 {
    ///                     ["A"] = new Dictionary&lt;string, object?&gt;
    ///                     {
    ///                         ["dataSource"] = "logs",
    ///                         ["queryName"] = "A",
    ///                         ["aggregateOperator"] = "noop",
    ///                         ["expression"] = "A",
    ///                         ["disabled"] = false,
    ///                     },
    ///                 },
    ///             },
    ///         }),
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SignozResourceType("signoz:index/savedView:SavedView")]
    public partial class SavedView : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        /// </summary>
        [Output("data")]
        public Output<string> Data { get; private set; } = null!;

        /// <summary>
        /// View name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Explorer the view belongs to: `Logs` or `Traces`.
        /// </summary>
        [Output("sourcePage")]
        public Output<string> SourcePage { get; private set; } = null!;


        /// <summary>
        /// Create a SavedView resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SavedView(string name, SavedViewArgs args, CustomResourceOptions? options = null)
            : base("signoz:index/savedView:SavedView", name, args ?? new SavedViewArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SavedView(string name, Input<string> id, SavedViewState? state = null, CustomResourceOptions? options = null)
            : base("signoz:index/savedView:SavedView", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SavedView resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SavedView Get(string name, Input<string> id, SavedViewState? state = null, CustomResourceOptions? options = null)
        {
            return new SavedView(name, id, state, options);
        }
    }

    public sealed class SavedViewArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        /// </summary>
        [Input("data", required: true)]
        public Input<string> Data { get; set; } = null!;

        /// <summary>
        /// View name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Explorer the view belongs to: `Logs` or `Traces`.
        /// </summary>
        [Input("sourcePage", required: true)]
        public Input<string> SourcePage { get; set; } = null!;

        public SavedViewArgs()
        {
        }
        public static new SavedViewArgs Empty => new SavedViewArgs();
    }

    public sealed class SavedViewState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
        /// </summary>
        [Input("data")]
        public Input<string>? Data { get; set; }

        /// <summary>
        /// View name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Explorer the view belongs to: `Logs` or `Traces`.
        /// </summary>
        [Input("sourcePage")]
        public Input<string>? SourcePage { get; set; }

        public SavedViewState()
        {
        }
        public static new SavedViewState Empty => new SavedViewState();
    }
}
