# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DashboardArgs', 'Dashboard']

@pulumi.input_type
class DashboardArgs:
    def __init__(__self__, *,
                 collapsable_rows_migrated: pulumi.Input[_builtins.bool],
                 description: pulumi.Input[_builtins.str],
                 layout: pulumi.Input[_builtins.str],
                 title: pulumi.Input[_builtins.str],
                 uploaded_grafana: pulumi.Input[_builtins.bool],
                 variables: pulumi.Input[_builtins.str],
                 version: pulumi.Input[_builtins.str],
                 widgets: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 panel_map: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Dashboard resource.

        :param pulumi.Input[_builtins.str] description: Description of the dashboard.
        :param pulumi.Input[_builtins.str] layout: Layout of the dashboard.
        :param pulumi.Input[_builtins.str] title: Title of the dashboard.
        :param pulumi.Input[_builtins.str] variables: Variables for the dashboard.
        :param pulumi.Input[_builtins.str] version: Version of the dashboard.
        :param pulumi.Input[_builtins.str] widgets: Widgets for the dashboard.
        :param pulumi.Input[_builtins.str] name: Name of the dashboard.
        :param pulumi.Input[_builtins.str] source: Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags of the dashboard.
        """
        pulumi.set(__self__, "collapsable_rows_migrated", collapsable_rows_migrated)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "layout", layout)
        pulumi.set(__self__, "title", title)
        pulumi.set(__self__, "uploaded_grafana", uploaded_grafana)
        pulumi.set(__self__, "variables", variables)
        pulumi.set(__self__, "version", version)
        pulumi.set(__self__, "widgets", widgets)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if panel_map is not None:
            pulumi.set(__self__, "panel_map", panel_map)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="collapsableRowsMigrated")
    def collapsable_rows_migrated(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "collapsable_rows_migrated")

    @collapsable_rows_migrated.setter
    def collapsable_rows_migrated(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "collapsable_rows_migrated", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str]:
        """
        Description of the dashboard.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def layout(self) -> pulumi.Input[_builtins.str]:
        """
        Layout of the dashboard.
        """
        return pulumi.get(self, "layout")

    @layout.setter
    def layout(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "layout", value)

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Input[_builtins.str]:
        """
        Title of the dashboard.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter(name="uploadedGrafana")
    def uploaded_grafana(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "uploaded_grafana")

    @uploaded_grafana.setter
    def uploaded_grafana(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "uploaded_grafana", value)

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Input[_builtins.str]:
        """
        Variables for the dashboard.
        """
        return pulumi.get(self, "variables")

    @variables.setter
    def variables(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "variables", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[_builtins.str]:
        """
        Version of the dashboard.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "version", value)

    @_builtins.property
    @pulumi.getter
    def widgets(self) -> pulumi.Input[_builtins.str]:
        """
        Widgets for the dashboard.
        """
        return pulumi.get(self, "widgets")

    @widgets.setter
    def widgets(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "widgets", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the dashboard.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="panelMap")
    def panel_map(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "panel_map")

    @panel_map.setter
    def panel_map(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "panel_map", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Tags of the dashboard.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.input_type
class _DashboardState:
    def __init__(__self__, *,
                 collapsable_rows_migrated: pulumi.Input[Optional[_builtins.bool]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 created_by: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 layout: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 panel_map: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_by: pulumi.Input[Optional[_builtins.str]] = None,
                 uploaded_grafana: pulumi.Input[Optional[_builtins.bool]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 widgets: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Dashboard resources.

        :param pulumi.Input[_builtins.str] created_at: Creation time of the dashboard.
        :param pulumi.Input[_builtins.str] created_by: Creator of the dashboard.
        :param pulumi.Input[_builtins.str] description: Description of the dashboard.
        :param pulumi.Input[_builtins.str] layout: Layout of the dashboard.
        :param pulumi.Input[_builtins.str] name: Name of the dashboard.
        :param pulumi.Input[_builtins.str] source: Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags of the dashboard.
        :param pulumi.Input[_builtins.str] title: Title of the dashboard.
        :param pulumi.Input[_builtins.str] updated_at: Last update time of the dashboard.
        :param pulumi.Input[_builtins.str] updated_by: Last updater of the dashboard.
        :param pulumi.Input[_builtins.str] variables: Variables for the dashboard.
        :param pulumi.Input[_builtins.str] version: Version of the dashboard.
        :param pulumi.Input[_builtins.str] widgets: Widgets for the dashboard.
        """
        if collapsable_rows_migrated is not None:
            pulumi.set(__self__, "collapsable_rows_migrated", collapsable_rows_migrated)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if created_by is not None:
            pulumi.set(__self__, "created_by", created_by)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if layout is not None:
            pulumi.set(__self__, "layout", layout)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if panel_map is not None:
            pulumi.set(__self__, "panel_map", panel_map)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if title is not None:
            pulumi.set(__self__, "title", title)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)
        if updated_by is not None:
            pulumi.set(__self__, "updated_by", updated_by)
        if uploaded_grafana is not None:
            pulumi.set(__self__, "uploaded_grafana", uploaded_grafana)
        if variables is not None:
            pulumi.set(__self__, "variables", variables)
        if version is not None:
            pulumi.set(__self__, "version", version)
        if widgets is not None:
            pulumi.set(__self__, "widgets", widgets)

    @_builtins.property
    @pulumi.getter(name="collapsableRowsMigrated")
    def collapsable_rows_migrated(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "collapsable_rows_migrated")

    @collapsable_rows_migrated.setter
    def collapsable_rows_migrated(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "collapsable_rows_migrated", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Creation time of the dashboard.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Creator of the dashboard.
        """
        return pulumi.get(self, "created_by")

    @created_by.setter
    def created_by(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_by", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the dashboard.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def layout(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Layout of the dashboard.
        """
        return pulumi.get(self, "layout")

    @layout.setter
    def layout(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "layout", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the dashboard.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="panelMap")
    def panel_map(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "panel_map")

    @panel_map.setter
    def panel_map(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "panel_map", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Tags of the dashboard.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Title of the dashboard.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Last update time of the dashboard.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)

    @_builtins.property
    @pulumi.getter(name="updatedBy")
    def updated_by(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Last updater of the dashboard.
        """
        return pulumi.get(self, "updated_by")

    @updated_by.setter
    def updated_by(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_by", value)

    @_builtins.property
    @pulumi.getter(name="uploadedGrafana")
    def uploaded_grafana(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "uploaded_grafana")

    @uploaded_grafana.setter
    def uploaded_grafana(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "uploaded_grafana", value)

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Variables for the dashboard.
        """
        return pulumi.get(self, "variables")

    @variables.setter
    def variables(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "variables", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Version of the dashboard.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)

    @_builtins.property
    @pulumi.getter
    def widgets(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Widgets for the dashboard.
        """
        return pulumi.get(self, "widgets")

    @widgets.setter
    def widgets(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "widgets", value)


@pulumi.type_token("signoz:index/dashboard:Dashboard")
class Dashboard(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collapsable_rows_migrated: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 layout: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 panel_map: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: pulumi.Input[Optional[_builtins.str]] = None,
                 uploaded_grafana: pulumi.Input[Optional[_builtins.bool]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 widgets: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Dashboard resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the dashboard.
        :param pulumi.Input[_builtins.str] layout: Layout of the dashboard.
        :param pulumi.Input[_builtins.str] name: Name of the dashboard.
        :param pulumi.Input[_builtins.str] source: Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags of the dashboard.
        :param pulumi.Input[_builtins.str] title: Title of the dashboard.
        :param pulumi.Input[_builtins.str] variables: Variables for the dashboard.
        :param pulumi.Input[_builtins.str] version: Version of the dashboard.
        :param pulumi.Input[_builtins.str] widgets: Widgets for the dashboard.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DashboardArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Dashboard resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param DashboardArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DashboardArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collapsable_rows_migrated: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 layout: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 panel_map: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: pulumi.Input[Optional[_builtins.str]] = None,
                 uploaded_grafana: pulumi.Input[Optional[_builtins.bool]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 widgets: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DashboardArgs.__new__(DashboardArgs)

            if collapsable_rows_migrated is None and not opts.urn:
                raise TypeError("Missing required property 'collapsable_rows_migrated'")
            __props__.__dict__["collapsable_rows_migrated"] = collapsable_rows_migrated
            if description is None and not opts.urn:
                raise TypeError("Missing required property 'description'")
            __props__.__dict__["description"] = description
            if layout is None and not opts.urn:
                raise TypeError("Missing required property 'layout'")
            __props__.__dict__["layout"] = layout
            __props__.__dict__["name"] = name
            __props__.__dict__["panel_map"] = panel_map
            __props__.__dict__["source"] = source
            __props__.__dict__["tags"] = tags
            if title is None and not opts.urn:
                raise TypeError("Missing required property 'title'")
            __props__.__dict__["title"] = title
            if uploaded_grafana is None and not opts.urn:
                raise TypeError("Missing required property 'uploaded_grafana'")
            __props__.__dict__["uploaded_grafana"] = uploaded_grafana
            if variables is None and not opts.urn:
                raise TypeError("Missing required property 'variables'")
            __props__.__dict__["variables"] = variables
            if version is None and not opts.urn:
                raise TypeError("Missing required property 'version'")
            __props__.__dict__["version"] = version
            if widgets is None and not opts.urn:
                raise TypeError("Missing required property 'widgets'")
            __props__.__dict__["widgets"] = widgets
            __props__.__dict__["created_at"] = None
            __props__.__dict__["created_by"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["updated_by"] = None
        super(Dashboard, __self__).__init__(
            'signoz:index/dashboard:Dashboard',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            collapsable_rows_migrated: pulumi.Input[Optional[_builtins.bool]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            created_by: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            layout: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            panel_map: pulumi.Input[Optional[_builtins.str]] = None,
            source: pulumi.Input[Optional[_builtins.str]] = None,
            tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            title: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None,
            updated_by: pulumi.Input[Optional[_builtins.str]] = None,
            uploaded_grafana: pulumi.Input[Optional[_builtins.bool]] = None,
            variables: pulumi.Input[Optional[_builtins.str]] = None,
            version: pulumi.Input[Optional[_builtins.str]] = None,
            widgets: pulumi.Input[Optional[_builtins.str]] = None) -> 'Dashboard':
        """
        Get an existing Dashboard resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: Creation time of the dashboard.
        :param pulumi.Input[_builtins.str] created_by: Creator of the dashboard.
        :param pulumi.Input[_builtins.str] description: Description of the dashboard.
        :param pulumi.Input[_builtins.str] layout: Layout of the dashboard.
        :param pulumi.Input[_builtins.str] name: Name of the dashboard.
        :param pulumi.Input[_builtins.str] source: Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags of the dashboard.
        :param pulumi.Input[_builtins.str] title: Title of the dashboard.
        :param pulumi.Input[_builtins.str] updated_at: Last update time of the dashboard.
        :param pulumi.Input[_builtins.str] updated_by: Last updater of the dashboard.
        :param pulumi.Input[_builtins.str] variables: Variables for the dashboard.
        :param pulumi.Input[_builtins.str] version: Version of the dashboard.
        :param pulumi.Input[_builtins.str] widgets: Widgets for the dashboard.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DashboardState.__new__(_DashboardState)

        __props__.__dict__["collapsable_rows_migrated"] = collapsable_rows_migrated
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["created_by"] = created_by
        __props__.__dict__["description"] = description
        __props__.__dict__["layout"] = layout
        __props__.__dict__["name"] = name
        __props__.__dict__["panel_map"] = panel_map
        __props__.__dict__["source"] = source
        __props__.__dict__["tags"] = tags
        __props__.__dict__["title"] = title
        __props__.__dict__["updated_at"] = updated_at
        __props__.__dict__["updated_by"] = updated_by
        __props__.__dict__["uploaded_grafana"] = uploaded_grafana
        __props__.__dict__["variables"] = variables
        __props__.__dict__["version"] = version
        __props__.__dict__["widgets"] = widgets
        return Dashboard(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="collapsableRowsMigrated")
    def collapsable_rows_migrated(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "collapsable_rows_migrated")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation time of the dashboard.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> pulumi.Output[_builtins.str]:
        """
        Creator of the dashboard.
        """
        return pulumi.get(self, "created_by")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        Description of the dashboard.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def layout(self) -> pulumi.Output[_builtins.str]:
        """
        Layout of the dashboard.
        """
        return pulumi.get(self, "layout")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the dashboard.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="panelMap")
    def panel_map(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "panel_map")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[_builtins.str]:
        """
        Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Tags of the dashboard.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Output[_builtins.str]:
        """
        Title of the dashboard.
        """
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Last update time of the dashboard.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="updatedBy")
    def updated_by(self) -> pulumi.Output[_builtins.str]:
        """
        Last updater of the dashboard.
        """
        return pulumi.get(self, "updated_by")

    @_builtins.property
    @pulumi.getter(name="uploadedGrafana")
    def uploaded_grafana(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "uploaded_grafana")

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Output[_builtins.str]:
        """
        Variables for the dashboard.
        """
        return pulumi.get(self, "variables")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        Version of the dashboard.
        """
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter
    def widgets(self) -> pulumi.Output[_builtins.str]:
        """
        Widgets for the dashboard.
        """
        return pulumi.get(self, "widgets")

