# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetAlertResult',
    'AwaitableGetAlertResult',
    'get_alert',
    'get_alert_output',
]

@pulumi.output_type
class GetAlertResult:
    """
    A collection of values returned by getAlert.
    """
    def __init__(__self__, alert=None, alert_type=None, broadcast_to_all=None, condition=None, description=None, disabled=None, eval_window=None, evaluation=None, frequency=None, id=None, labels=None, notification_settings=None, preferred_channels=None, rule_type=None, schema_version=None, severity=None, source=None, state=None, summary=None, version=None):
        if alert and not isinstance(alert, str):
            raise TypeError("Expected argument 'alert' to be a str")
        pulumi.set(__self__, "alert", alert)
        if alert_type and not isinstance(alert_type, str):
            raise TypeError("Expected argument 'alert_type' to be a str")
        pulumi.set(__self__, "alert_type", alert_type)
        if broadcast_to_all and not isinstance(broadcast_to_all, bool):
            raise TypeError("Expected argument 'broadcast_to_all' to be a bool")
        pulumi.set(__self__, "broadcast_to_all", broadcast_to_all)
        if condition and not isinstance(condition, str):
            raise TypeError("Expected argument 'condition' to be a str")
        pulumi.set(__self__, "condition", condition)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if disabled and not isinstance(disabled, bool):
            raise TypeError("Expected argument 'disabled' to be a bool")
        pulumi.set(__self__, "disabled", disabled)
        if eval_window and not isinstance(eval_window, str):
            raise TypeError("Expected argument 'eval_window' to be a str")
        pulumi.set(__self__, "eval_window", eval_window)
        if evaluation and not isinstance(evaluation, str):
            raise TypeError("Expected argument 'evaluation' to be a str")
        pulumi.set(__self__, "evaluation", evaluation)
        if frequency and not isinstance(frequency, str):
            raise TypeError("Expected argument 'frequency' to be a str")
        pulumi.set(__self__, "frequency", frequency)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if notification_settings and not isinstance(notification_settings, dict):
            raise TypeError("Expected argument 'notification_settings' to be a dict")
        pulumi.set(__self__, "notification_settings", notification_settings)
        if preferred_channels and not isinstance(preferred_channels, list):
            raise TypeError("Expected argument 'preferred_channels' to be a list")
        pulumi.set(__self__, "preferred_channels", preferred_channels)
        if rule_type and not isinstance(rule_type, str):
            raise TypeError("Expected argument 'rule_type' to be a str")
        pulumi.set(__self__, "rule_type", rule_type)
        if schema_version and not isinstance(schema_version, str):
            raise TypeError("Expected argument 'schema_version' to be a str")
        pulumi.set(__self__, "schema_version", schema_version)
        if severity and not isinstance(severity, str):
            raise TypeError("Expected argument 'severity' to be a str")
        pulumi.set(__self__, "severity", severity)
        if source and not isinstance(source, str):
            raise TypeError("Expected argument 'source' to be a str")
        pulumi.set(__self__, "source", source)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if summary and not isinstance(summary, str):
            raise TypeError("Expected argument 'summary' to be a str")
        pulumi.set(__self__, "summary", summary)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def alert(self) -> _builtins.str:
        return pulumi.get(self, "alert")

    @_builtins.property
    @pulumi.getter(name="alertType")
    def alert_type(self) -> _builtins.str:
        return pulumi.get(self, "alert_type")

    @_builtins.property
    @pulumi.getter(name="broadcastToAll")
    @_utilities.deprecated("""This field is no longer needed and will be ignored""")
    def broadcast_to_all(self) -> _builtins.bool:
        return pulumi.get(self, "broadcast_to_all")

    @_builtins.property
    @pulumi.getter
    def condition(self) -> _builtins.str:
        return pulumi.get(self, "condition")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> _builtins.bool:
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="evalWindow")
    def eval_window(self) -> _builtins.str:
        return pulumi.get(self, "eval_window")

    @_builtins.property
    @pulumi.getter
    def evaluation(self) -> _builtins.str:
        return pulumi.get(self, "evaluation")

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> _builtins.str:
        return pulumi.get(self, "frequency")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="notificationSettings")
    def notification_settings(self) -> 'outputs.GetAlertNotificationSettingsResult':
        return pulumi.get(self, "notification_settings")

    @_builtins.property
    @pulumi.getter(name="preferredChannels")
    def preferred_channels(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "preferred_channels")

    @_builtins.property
    @pulumi.getter(name="ruleType")
    def rule_type(self) -> _builtins.str:
        return pulumi.get(self, "rule_type")

    @_builtins.property
    @pulumi.getter(name="schemaVersion")
    def schema_version(self) -> _builtins.str:
        return pulumi.get(self, "schema_version")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> _builtins.str:
        return pulumi.get(self, "severity")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def summary(self) -> _builtins.str:
        return pulumi.get(self, "summary")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")


class AwaitableGetAlertResult(GetAlertResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAlertResult(
            alert=self.alert,
            alert_type=self.alert_type,
            broadcast_to_all=self.broadcast_to_all,
            condition=self.condition,
            description=self.description,
            disabled=self.disabled,
            eval_window=self.eval_window,
            evaluation=self.evaluation,
            frequency=self.frequency,
            id=self.id,
            labels=self.labels,
            notification_settings=self.notification_settings,
            preferred_channels=self.preferred_channels,
            rule_type=self.rule_type,
            schema_version=self.schema_version,
            severity=self.severity,
            source=self.source,
            state=self.state,
            summary=self.summary,
            version=self.version)


def get_alert(id: Optional[_builtins.str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAlertResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('signoz:index/getAlert:getAlert', __args__, opts=opts, typ=GetAlertResult).value

    return AwaitableGetAlertResult(
        alert=pulumi.get(__ret__, 'alert'),
        alert_type=pulumi.get(__ret__, 'alert_type'),
        broadcast_to_all=pulumi.get(__ret__, 'broadcast_to_all'),
        condition=pulumi.get(__ret__, 'condition'),
        description=pulumi.get(__ret__, 'description'),
        disabled=pulumi.get(__ret__, 'disabled'),
        eval_window=pulumi.get(__ret__, 'eval_window'),
        evaluation=pulumi.get(__ret__, 'evaluation'),
        frequency=pulumi.get(__ret__, 'frequency'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        notification_settings=pulumi.get(__ret__, 'notification_settings'),
        preferred_channels=pulumi.get(__ret__, 'preferred_channels'),
        rule_type=pulumi.get(__ret__, 'rule_type'),
        schema_version=pulumi.get(__ret__, 'schema_version'),
        severity=pulumi.get(__ret__, 'severity'),
        source=pulumi.get(__ret__, 'source'),
        state=pulumi.get(__ret__, 'state'),
        summary=pulumi.get(__ret__, 'summary'),
        version=pulumi.get(__ret__, 'version'))
def get_alert_output(id: pulumi.Input[Optional[_builtins.str]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAlertResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('signoz:index/getAlert:getAlert', __args__, opts=opts, typ=GetAlertResult)
    return __ret__.apply(lambda __response__: GetAlertResult(
        alert=pulumi.get(__response__, 'alert'),
        alert_type=pulumi.get(__response__, 'alert_type'),
        broadcast_to_all=pulumi.get(__response__, 'broadcast_to_all'),
        condition=pulumi.get(__response__, 'condition'),
        description=pulumi.get(__response__, 'description'),
        disabled=pulumi.get(__response__, 'disabled'),
        eval_window=pulumi.get(__response__, 'eval_window'),
        evaluation=pulumi.get(__response__, 'evaluation'),
        frequency=pulumi.get(__response__, 'frequency'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        notification_settings=pulumi.get(__response__, 'notification_settings'),
        preferred_channels=pulumi.get(__response__, 'preferred_channels'),
        rule_type=pulumi.get(__response__, 'rule_type'),
        schema_version=pulumi.get(__response__, 'schema_version'),
        severity=pulumi.get(__response__, 'severity'),
        source=pulumi.get(__response__, 'source'),
        state=pulumi.get(__response__, 'state'),
        summary=pulumi.get(__response__, 'summary'),
        version=pulumi.get(__response__, 'version')))
