# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetDashboardResult',
    'AwaitableGetDashboardResult',
    'get_dashboard',
    'get_dashboard_output',
]

@pulumi.output_type
class GetDashboardResult:
    """
    A collection of values returned by getDashboard.
    """
    def __init__(__self__, collapsable_rows_migrated=None, description=None, id=None, layout=None, name=None, panel_map=None, source=None, tags=None, title=None, uploaded_grafana=None, variables=None, version=None, widgets=None):
        if collapsable_rows_migrated and not isinstance(collapsable_rows_migrated, bool):
            raise TypeError("Expected argument 'collapsable_rows_migrated' to be a bool")
        pulumi.set(__self__, "collapsable_rows_migrated", collapsable_rows_migrated)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if layout and not isinstance(layout, str):
            raise TypeError("Expected argument 'layout' to be a str")
        pulumi.set(__self__, "layout", layout)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if panel_map and not isinstance(panel_map, str):
            raise TypeError("Expected argument 'panel_map' to be a str")
        pulumi.set(__self__, "panel_map", panel_map)
        if source and not isinstance(source, str):
            raise TypeError("Expected argument 'source' to be a str")
        pulumi.set(__self__, "source", source)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if title and not isinstance(title, str):
            raise TypeError("Expected argument 'title' to be a str")
        pulumi.set(__self__, "title", title)
        if uploaded_grafana and not isinstance(uploaded_grafana, bool):
            raise TypeError("Expected argument 'uploaded_grafana' to be a bool")
        pulumi.set(__self__, "uploaded_grafana", uploaded_grafana)
        if variables and not isinstance(variables, str):
            raise TypeError("Expected argument 'variables' to be a str")
        pulumi.set(__self__, "variables", variables)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)
        if widgets and not isinstance(widgets, str):
            raise TypeError("Expected argument 'widgets' to be a str")
        pulumi.set(__self__, "widgets", widgets)

    @_builtins.property
    @pulumi.getter(name="collapsableRowsMigrated")
    def collapsable_rows_migrated(self) -> _builtins.bool:
        return pulumi.get(self, "collapsable_rows_migrated")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def layout(self) -> _builtins.str:
        return pulumi.get(self, "layout")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="panelMap")
    def panel_map(self) -> _builtins.str:
        return pulumi.get(self, "panel_map")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def title(self) -> _builtins.str:
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter(name="uploadedGrafana")
    def uploaded_grafana(self) -> _builtins.bool:
        return pulumi.get(self, "uploaded_grafana")

    @_builtins.property
    @pulumi.getter
    def variables(self) -> _builtins.str:
        return pulumi.get(self, "variables")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter
    def widgets(self) -> _builtins.str:
        return pulumi.get(self, "widgets")


class AwaitableGetDashboardResult(GetDashboardResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDashboardResult(
            collapsable_rows_migrated=self.collapsable_rows_migrated,
            description=self.description,
            id=self.id,
            layout=self.layout,
            name=self.name,
            panel_map=self.panel_map,
            source=self.source,
            tags=self.tags,
            title=self.title,
            uploaded_grafana=self.uploaded_grafana,
            variables=self.variables,
            version=self.version,
            widgets=self.widgets)


def get_dashboard(id: Optional[_builtins.str] = None,
                  version: Optional[_builtins.str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDashboardResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['version'] = version
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('signoz:index/getDashboard:getDashboard', __args__, opts=opts, typ=GetDashboardResult).value

    return AwaitableGetDashboardResult(
        collapsable_rows_migrated=pulumi.get(__ret__, 'collapsable_rows_migrated'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        layout=pulumi.get(__ret__, 'layout'),
        name=pulumi.get(__ret__, 'name'),
        panel_map=pulumi.get(__ret__, 'panel_map'),
        source=pulumi.get(__ret__, 'source'),
        tags=pulumi.get(__ret__, 'tags'),
        title=pulumi.get(__ret__, 'title'),
        uploaded_grafana=pulumi.get(__ret__, 'uploaded_grafana'),
        variables=pulumi.get(__ret__, 'variables'),
        version=pulumi.get(__ret__, 'version'),
        widgets=pulumi.get(__ret__, 'widgets'))
def get_dashboard_output(id: pulumi.Input[Optional[_builtins.str]] = None,
                         version: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDashboardResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['version'] = version
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('signoz:index/getDashboard:getDashboard', __args__, opts=opts, typ=GetDashboardResult)
    return __ret__.apply(lambda __response__: GetDashboardResult(
        collapsable_rows_migrated=pulumi.get(__response__, 'collapsable_rows_migrated'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        layout=pulumi.get(__response__, 'layout'),
        name=pulumi.get(__response__, 'name'),
        panel_map=pulumi.get(__response__, 'panel_map'),
        source=pulumi.get(__response__, 'source'),
        tags=pulumi.get(__response__, 'tags'),
        title=pulumi.get(__response__, 'title'),
        uploaded_grafana=pulumi.get(__response__, 'uploaded_grafana'),
        variables=pulumi.get(__response__, 'variables'),
        version=pulumi.get(__response__, 'version'),
        widgets=pulumi.get(__response__, 'widgets')))
