# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'AlertNotificationSettings',
    'AlertNotificationSettingsRenotify',
    'GetAlertNotificationSettingsResult',
    'GetAlertNotificationSettingsRenotifyResult',
]

@pulumi.output_type
class AlertNotificationSettings(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "groupBies":
            suggest = "group_bies"
        elif key == "usePolicy":
            suggest = "use_policy"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AlertNotificationSettings. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AlertNotificationSettings.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AlertNotificationSettings.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 group_bies: Optional[Sequence[_builtins.str]] = None,
                 renotify: Optional['outputs.AlertNotificationSettingsRenotify'] = None,
                 use_policy: Optional[_builtins.bool] = None):
        """
        :param Sequence[_builtins.str] group_bies: Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
        :param 'AlertNotificationSettingsRenotifyArgs' renotify: The alert re-notification settings.
        :param _builtins.bool use_policy: Use policy in the alert. By default, it is false.
        """
        if group_bies is not None:
            pulumi.set(__self__, "group_bies", group_bies)
        if renotify is not None:
            pulumi.set(__self__, "renotify", renotify)
        if use_policy is not None:
            pulumi.set(__self__, "use_policy", use_policy)

    @_builtins.property
    @pulumi.getter(name="groupBies")
    def group_bies(self) -> Optional[Sequence[_builtins.str]]:
        """
        Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
        """
        return pulumi.get(self, "group_bies")

    @_builtins.property
    @pulumi.getter
    def renotify(self) -> Optional['outputs.AlertNotificationSettingsRenotify']:
        """
        The alert re-notification settings.
        """
        return pulumi.get(self, "renotify")

    @_builtins.property
    @pulumi.getter(name="usePolicy")
    def use_policy(self) -> Optional[_builtins.bool]:
        """
        Use policy in the alert. By default, it is false.
        """
        return pulumi.get(self, "use_policy")


@pulumi.output_type
class AlertNotificationSettingsRenotify(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "alertStates":
            suggest = "alert_states"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AlertNotificationSettingsRenotify. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AlertNotificationSettingsRenotify.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AlertNotificationSettingsRenotify.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 alert_states: Sequence[_builtins.str],
                 interval: _builtins.str,
                 enabled: Optional[_builtins.bool] = None):
        """
        :param Sequence[_builtins.str] alert_states: For which AlertStates of the alert want to get renotified.
        :param _builtins.str interval: Re-notify interval of the alert.
        :param _builtins.bool enabled: To enable the re-notification of the alert.
        """
        pulumi.set(__self__, "alert_states", alert_states)
        pulumi.set(__self__, "interval", interval)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter(name="alertStates")
    def alert_states(self) -> Sequence[_builtins.str]:
        """
        For which AlertStates of the alert want to get renotified.
        """
        return pulumi.get(self, "alert_states")

    @_builtins.property
    @pulumi.getter
    def interval(self) -> _builtins.str:
        """
        Re-notify interval of the alert.
        """
        return pulumi.get(self, "interval")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        To enable the re-notification of the alert.
        """
        return pulumi.get(self, "enabled")


@pulumi.output_type
class GetAlertNotificationSettingsResult(dict):
    def __init__(__self__, *,
                 group_bies: Sequence[_builtins.str],
                 renotify: 'outputs.GetAlertNotificationSettingsRenotifyResult',
                 use_policy: _builtins.bool):
        """
        :param Sequence[_builtins.str] group_bies: Group by labels for notification.
        :param 'GetAlertNotificationSettingsRenotifyArgs' renotify: Renotify settings for the alert.
        :param _builtins.bool use_policy: Whether to use notification policy.
        """
        pulumi.set(__self__, "group_bies", group_bies)
        pulumi.set(__self__, "renotify", renotify)
        pulumi.set(__self__, "use_policy", use_policy)

    @_builtins.property
    @pulumi.getter(name="groupBies")
    def group_bies(self) -> Sequence[_builtins.str]:
        """
        Group by labels for notification.
        """
        return pulumi.get(self, "group_bies")

    @_builtins.property
    @pulumi.getter
    def renotify(self) -> 'outputs.GetAlertNotificationSettingsRenotifyResult':
        """
        Renotify settings for the alert.
        """
        return pulumi.get(self, "renotify")

    @_builtins.property
    @pulumi.getter(name="usePolicy")
    def use_policy(self) -> _builtins.bool:
        """
        Whether to use notification policy.
        """
        return pulumi.get(self, "use_policy")


@pulumi.output_type
class GetAlertNotificationSettingsRenotifyResult(dict):
    def __init__(__self__, *,
                 alert_states: Sequence[_builtins.str],
                 enabled: _builtins.bool,
                 interval: _builtins.str):
        """
        :param Sequence[_builtins.str] alert_states: Alert states for renotify.
        :param _builtins.bool enabled: Whether renotify is enabled.
        :param _builtins.str interval: Interval for renotify.
        """
        pulumi.set(__self__, "alert_states", alert_states)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "interval", interval)

    @_builtins.property
    @pulumi.getter(name="alertStates")
    def alert_states(self) -> Sequence[_builtins.str]:
        """
        Alert states for renotify.
        """
        return pulumi.get(self, "alert_states")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Whether renotify is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def interval(self) -> _builtins.str:
        """
        Interval for renotify.
        """
        return pulumi.get(self, "interval")


