// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jooon.Pulumi.Signoz.Outputs
{

    [OutputType]
    public sealed class AlertNotificationSettings
    {
        /// <summary>
        /// Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
        /// </summary>
        public readonly ImmutableArray<string> GroupBies;
        /// <summary>
        /// The alert re-notification settings.
        /// </summary>
        public readonly Outputs.AlertNotificationSettingsRenotify? Renotify;
        /// <summary>
        /// Use policy in the alert. By default, it is false.
        /// </summary>
        public readonly bool? UsePolicy;

        [OutputConstructor]
        private AlertNotificationSettings(
            ImmutableArray<string> groupBies,

            Outputs.AlertNotificationSettingsRenotify? renotify,

            bool? usePolicy)
        {
            GroupBies = groupBies;
            Renotify = renotify;
            UsePolicy = usePolicy;
        }
    }
}
