// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JGautheron.Pulumi.Signoz.Outputs
{

    [OutputType]
    public sealed class AlertNotificationSettingsRenotify
    {
        /// <summary>
        /// For which AlertStates of the alert want to get renotified.
        /// </summary>
        public readonly ImmutableArray<string> AlertStates;
        /// <summary>
        /// To enable the re-notification of the alert.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Re-notify interval of the alert.
        /// </summary>
        public readonly string Interval;

        [OutputConstructor]
        private AlertNotificationSettingsRenotify(
            ImmutableArray<string> alertStates,

            bool? enabled,

            string interval)
        {
            AlertStates = alertStates;
            Enabled = enabled;
            Interval = interval;
        }
    }
}
