// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JGautheron.Pulumi.Signoz.Outputs
{

    [OutputType]
    public sealed class GetAlertNotificationSettingsRenotifyResult
    {
        /// <summary>
        /// Alert states for renotify.
        /// </summary>
        public readonly ImmutableArray<string> AlertStates;
        /// <summary>
        /// Whether renotify is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Interval for renotify.
        /// </summary>
        public readonly string Interval;

        [OutputConstructor]
        private GetAlertNotificationSettingsRenotifyResult(
            ImmutableArray<string> alertStates,

            bool enabled,

            string interval)
        {
            AlertStates = alertStates;
            Enabled = enabled;
            Interval = interval;
        }
    }
}
