// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A SigNoz alert rule. Top-level fields are typed; the query `condition`, `evaluation`, and `notificationSettings` are JSON blobs (export from the SigNoz UI to adapt). Defaults target the v5 / v2alpha1 schema required by SigNoz >= 0.125.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as signoz from "@jooon/pulumi-signoz";
 *
 * // A logs-based alert on the v5 / v2alpha1 schema (SigNoz >= 0.125).
 * // The threshold references a notification channel by name.
 * const highErrorLogs = new signoz.Alert("high_error_logs", {
 *     alert: "High error log volume",
 *     alertType: "LOGS_BASED_ALERT",
 *     severity: "warning",
 *     condition: JSON.stringify({
 *         compositeQuery: {
 *             queryType: "builder",
 *             panelType: "graph",
 *             queries: [{
 *                 type: "builder_query",
 *                 spec: {
 *                     name: "A",
 *                     signal: "logs",
 *                     stepInterval: 0,
 *                     aggregations: [{
 *                         expression: "count()",
 *                     }],
 *                     filter: {
 *                         expression: "severity_text = 'ERROR'",
 *                     },
 *                     having: {
 *                         expression: "",
 *                     },
 *                 },
 *             }],
 *         },
 *         selectedQueryName: "A",
 *         thresholds: {
 *             kind: "basic",
 *             spec: [{
 *                 name: "warning",
 *                 target: 100,
 *                 matchType: "1",
 *                 op: "1",
 *                 channels: [slack.name],
 *             }],
 *         },
 *     }),
 *     evaluation: JSON.stringify({
 *         kind: "rolling",
 *         spec: {
 *             evalWindow: "5m0s",
 *             frequency: "1m0s",
 *         },
 *     }),
 *     preferredChannels: [slack.name],
 * });
 * ```
 */
export class Alert extends pulumi.CustomResource {
    /**
     * Get an existing Alert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertState, opts?: pulumi.CustomResourceOptions): Alert {
        return new Alert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'signoz:index/alert:Alert';

    /**
     * Returns true if the given object is an instance of Alert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Alert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Alert.__pulumiType;
    }

    /**
     * Alert name.
     */
    declare public readonly alert: pulumi.Output<string>;
    /**
     * One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
     */
    declare public readonly alertType: pulumi.Output<string>;
    /**
     * Query condition as JSON (compositeQuery + thresholds). Compared semantically.
     */
    declare public readonly condition: pulumi.Output<string>;
    /**
     * Human-readable description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether the rule is disabled. Defaults to false.
     */
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * Evaluation window (e.g. `5m0s`).
     */
    declare public readonly evalWindow: pulumi.Output<string>;
    /**
     * Evaluation block as JSON (v2alpha1+). Compared semantically.
     */
    declare public readonly evaluation: pulumi.Output<string | undefined>;
    /**
     * Evaluation frequency (e.g. `1m0s`).
     */
    declare public readonly frequency: pulumi.Output<string>;
    /**
     * Custom labels attached to the alert.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
     */
    declare public readonly notificationSettings: pulumi.Output<string | undefined>;
    /**
     * Notification channel names the alert routes to.
     */
    declare public readonly preferredChannels: pulumi.Output<string[] | undefined>;
    /**
     * Rule engine type: `thresholdRule` (default) or `promqlRule`.
     */
    declare public readonly ruleType: pulumi.Output<string>;
    /**
     * Alert schema version. Defaults to `v2alpha1`.
     */
    declare public readonly schemaVersion: pulumi.Output<string>;
    /**
     * Severity label (e.g. `info`, `warning`, `critical`).
     */
    declare public readonly severity: pulumi.Output<string | undefined>;
    /**
     * Source URL recorded on the rule.
     */
    declare public readonly source: pulumi.Output<string | undefined>;
    /**
     * Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
     */
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a Alert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertArgs | AlertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertState | undefined;
            resourceInputs["alert"] = state?.alert;
            resourceInputs["alertType"] = state?.alertType;
            resourceInputs["condition"] = state?.condition;
            resourceInputs["description"] = state?.description;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["evalWindow"] = state?.evalWindow;
            resourceInputs["evaluation"] = state?.evaluation;
            resourceInputs["frequency"] = state?.frequency;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["notificationSettings"] = state?.notificationSettings;
            resourceInputs["preferredChannels"] = state?.preferredChannels;
            resourceInputs["ruleType"] = state?.ruleType;
            resourceInputs["schemaVersion"] = state?.schemaVersion;
            resourceInputs["severity"] = state?.severity;
            resourceInputs["source"] = state?.source;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as AlertArgs | undefined;
            if (args?.alert === undefined && !opts.urn) {
                throw new Error("Missing required property 'alert'");
            }
            if (args?.alertType === undefined && !opts.urn) {
                throw new Error("Missing required property 'alertType'");
            }
            if (args?.condition === undefined && !opts.urn) {
                throw new Error("Missing required property 'condition'");
            }
            resourceInputs["alert"] = args?.alert;
            resourceInputs["alertType"] = args?.alertType;
            resourceInputs["condition"] = args?.condition;
            resourceInputs["description"] = args?.description;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["evalWindow"] = args?.evalWindow;
            resourceInputs["evaluation"] = args?.evaluation;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["notificationSettings"] = args?.notificationSettings;
            resourceInputs["preferredChannels"] = args?.preferredChannels;
            resourceInputs["ruleType"] = args?.ruleType;
            resourceInputs["schemaVersion"] = args?.schemaVersion;
            resourceInputs["severity"] = args?.severity;
            resourceInputs["source"] = args?.source;
            resourceInputs["version"] = args?.version;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Alert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Alert resources.
 */
export interface AlertState {
    /**
     * Alert name.
     */
    alert?: pulumi.Input<string | undefined>;
    /**
     * One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
     */
    alertType?: pulumi.Input<string | undefined>;
    /**
     * Query condition as JSON (compositeQuery + thresholds). Compared semantically.
     */
    condition?: pulumi.Input<string | undefined>;
    /**
     * Human-readable description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the rule is disabled. Defaults to false.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * Evaluation window (e.g. `5m0s`).
     */
    evalWindow?: pulumi.Input<string | undefined>;
    /**
     * Evaluation block as JSON (v2alpha1+). Compared semantically.
     */
    evaluation?: pulumi.Input<string | undefined>;
    /**
     * Evaluation frequency (e.g. `1m0s`).
     */
    frequency?: pulumi.Input<string | undefined>;
    /**
     * Custom labels attached to the alert.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
     */
    notificationSettings?: pulumi.Input<string | undefined>;
    /**
     * Notification channel names the alert routes to.
     */
    preferredChannels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Rule engine type: `thresholdRule` (default) or `promqlRule`.
     */
    ruleType?: pulumi.Input<string | undefined>;
    /**
     * Alert schema version. Defaults to `v2alpha1`.
     */
    schemaVersion?: pulumi.Input<string | undefined>;
    /**
     * Severity label (e.g. `info`, `warning`, `critical`).
     */
    severity?: pulumi.Input<string | undefined>;
    /**
     * Source URL recorded on the rule.
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Alert resource.
 */
export interface AlertArgs {
    /**
     * Alert name.
     */
    alert: pulumi.Input<string>;
    /**
     * One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
     */
    alertType: pulumi.Input<string>;
    /**
     * Query condition as JSON (compositeQuery + thresholds). Compared semantically.
     */
    condition: pulumi.Input<string>;
    /**
     * Human-readable description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the rule is disabled. Defaults to false.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * Evaluation window (e.g. `5m0s`).
     */
    evalWindow?: pulumi.Input<string | undefined>;
    /**
     * Evaluation block as JSON (v2alpha1+). Compared semantically.
     */
    evaluation?: pulumi.Input<string | undefined>;
    /**
     * Evaluation frequency (e.g. `1m0s`).
     */
    frequency?: pulumi.Input<string | undefined>;
    /**
     * Custom labels attached to the alert.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Notification settings as JSON (renotify, group*by, use*policy). Compared semantically.
     */
    notificationSettings?: pulumi.Input<string | undefined>;
    /**
     * Notification channel names the alert routes to.
     */
    preferredChannels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Rule engine type: `thresholdRule` (default) or `promqlRule`.
     */
    ruleType?: pulumi.Input<string | undefined>;
    /**
     * Alert schema version. Defaults to `v2alpha1`.
     */
    schemaVersion?: pulumi.Input<string | undefined>;
    /**
     * Severity label (e.g. `info`, `warning`, `critical`).
     */
    severity?: pulumi.Input<string | undefined>;
    /**
     * Source URL recorded on the rule.
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
     */
    version?: pulumi.Input<string | undefined>;
}
