// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Alert extends pulumi.CustomResource {
    /**
     * Get an existing Alert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertState, opts?: pulumi.CustomResourceOptions): Alert {
        return new Alert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'signoz:index/alert:Alert';

    /**
     * Returns true if the given object is an instance of Alert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Alert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Alert.__pulumiType;
    }

    /**
     * Name of the alert.
     */
    declare public readonly alert: pulumi.Output<string>;
    /**
     * Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
     */
    declare public readonly alertType: pulumi.Output<string>;
    /**
     * Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
     *
     * @deprecated This field is no longer needed and will be ignored
     */
    declare public readonly broadcastToAll: pulumi.Output<boolean>;
    /**
     * Condition of the alert.
     */
    declare public readonly condition: pulumi.Output<string>;
    /**
     * Creation time of the alert.
     */
    declare public /*out*/ readonly createAt: pulumi.Output<string>;
    /**
     * Creator of the alert.
     */
    declare public /*out*/ readonly createBy: pulumi.Output<string>;
    /**
     * Description of the alert.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Whether the alert is disabled.
     */
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * The evaluation window of the alert. By default, it is 5m0s.
     */
    declare public readonly evalWindow: pulumi.Output<string>;
    /**
     * Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
     */
    declare public readonly evaluation: pulumi.Output<string>;
    /**
     * The frequency of the alert. By default, it is 1m0s.
     */
    declare public readonly frequency: pulumi.Output<string>;
    /**
     * Labels of the alert. Severity is a required label.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string}>;
    /**
     * Notification settings for the alert. Only used when schemaVersion is v2 or higher.
     */
    declare public readonly notificationSettings: pulumi.Output<outputs.AlertNotificationSettings>;
    /**
     * Preferred channels of the alert. By default, it is empty.
     */
    declare public readonly preferredChannels: pulumi.Output<string[]>;
    /**
     * Type of the alert. Possible values are: thresholdRule and promql_rule.
     */
    declare public readonly ruleType: pulumi.Output<string>;
    /**
     * Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
     */
    declare public readonly schemaVersion: pulumi.Output<string>;
    /**
     * Severity of the alert. Possible values are: info, warning, error, and critical.
     */
    declare public readonly severity: pulumi.Output<string>;
    /**
     * Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
     */
    declare public readonly source: pulumi.Output<string>;
    /**
     * State of the alert.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Summary of the alert.
     */
    declare public readonly summary: pulumi.Output<string>;
    /**
     * Last update time of the alert.
     */
    declare public /*out*/ readonly updateAt: pulumi.Output<string>;
    /**
     * Last updater of the alert.
     */
    declare public /*out*/ readonly updateBy: pulumi.Output<string>;
    /**
     * Version of the alert. By default, it is v4.
     */
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a Alert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertArgs | AlertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertState | undefined;
            resourceInputs["alert"] = state?.alert;
            resourceInputs["alertType"] = state?.alertType;
            resourceInputs["broadcastToAll"] = state?.broadcastToAll;
            resourceInputs["condition"] = state?.condition;
            resourceInputs["createAt"] = state?.createAt;
            resourceInputs["createBy"] = state?.createBy;
            resourceInputs["description"] = state?.description;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["evalWindow"] = state?.evalWindow;
            resourceInputs["evaluation"] = state?.evaluation;
            resourceInputs["frequency"] = state?.frequency;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["notificationSettings"] = state?.notificationSettings;
            resourceInputs["preferredChannels"] = state?.preferredChannels;
            resourceInputs["ruleType"] = state?.ruleType;
            resourceInputs["schemaVersion"] = state?.schemaVersion;
            resourceInputs["severity"] = state?.severity;
            resourceInputs["source"] = state?.source;
            resourceInputs["state"] = state?.state;
            resourceInputs["summary"] = state?.summary;
            resourceInputs["updateAt"] = state?.updateAt;
            resourceInputs["updateBy"] = state?.updateBy;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as AlertArgs | undefined;
            if (args?.alert === undefined && !opts.urn) {
                throw new Error("Missing required property 'alert'");
            }
            if (args?.alertType === undefined && !opts.urn) {
                throw new Error("Missing required property 'alertType'");
            }
            if (args?.condition === undefined && !opts.urn) {
                throw new Error("Missing required property 'condition'");
            }
            if (args?.severity === undefined && !opts.urn) {
                throw new Error("Missing required property 'severity'");
            }
            resourceInputs["alert"] = args?.alert;
            resourceInputs["alertType"] = args?.alertType;
            resourceInputs["broadcastToAll"] = args?.broadcastToAll;
            resourceInputs["condition"] = args?.condition;
            resourceInputs["description"] = args?.description;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["evalWindow"] = args?.evalWindow;
            resourceInputs["evaluation"] = args?.evaluation;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["notificationSettings"] = args?.notificationSettings;
            resourceInputs["preferredChannels"] = args?.preferredChannels;
            resourceInputs["ruleType"] = args?.ruleType;
            resourceInputs["schemaVersion"] = args?.schemaVersion;
            resourceInputs["severity"] = args?.severity;
            resourceInputs["source"] = args?.source;
            resourceInputs["summary"] = args?.summary;
            resourceInputs["version"] = args?.version;
            resourceInputs["createAt"] = undefined /*out*/;
            resourceInputs["createBy"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["updateAt"] = undefined /*out*/;
            resourceInputs["updateBy"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Alert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Alert resources.
 */
export interface AlertState {
    /**
     * Name of the alert.
     */
    alert?: pulumi.Input<string | undefined>;
    /**
     * Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
     */
    alertType?: pulumi.Input<string | undefined>;
    /**
     * Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
     *
     * @deprecated This field is no longer needed and will be ignored
     */
    broadcastToAll?: pulumi.Input<boolean | undefined>;
    /**
     * Condition of the alert.
     */
    condition?: pulumi.Input<string | undefined>;
    /**
     * Creation time of the alert.
     */
    createAt?: pulumi.Input<string | undefined>;
    /**
     * Creator of the alert.
     */
    createBy?: pulumi.Input<string | undefined>;
    /**
     * Description of the alert.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the alert is disabled.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The evaluation window of the alert. By default, it is 5m0s.
     */
    evalWindow?: pulumi.Input<string | undefined>;
    /**
     * Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
     */
    evaluation?: pulumi.Input<string | undefined>;
    /**
     * The frequency of the alert. By default, it is 1m0s.
     */
    frequency?: pulumi.Input<string | undefined>;
    /**
     * Labels of the alert. Severity is a required label.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Notification settings for the alert. Only used when schemaVersion is v2 or higher.
     */
    notificationSettings?: pulumi.Input<inputs.AlertNotificationSettings | undefined>;
    /**
     * Preferred channels of the alert. By default, it is empty.
     */
    preferredChannels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Type of the alert. Possible values are: thresholdRule and promql_rule.
     */
    ruleType?: pulumi.Input<string | undefined>;
    /**
     * Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
     */
    schemaVersion?: pulumi.Input<string | undefined>;
    /**
     * Severity of the alert. Possible values are: info, warning, error, and critical.
     */
    severity?: pulumi.Input<string | undefined>;
    /**
     * Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * State of the alert.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * Summary of the alert.
     */
    summary?: pulumi.Input<string | undefined>;
    /**
     * Last update time of the alert.
     */
    updateAt?: pulumi.Input<string | undefined>;
    /**
     * Last updater of the alert.
     */
    updateBy?: pulumi.Input<string | undefined>;
    /**
     * Version of the alert. By default, it is v4.
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Alert resource.
 */
export interface AlertArgs {
    /**
     * Name of the alert.
     */
    alert: pulumi.Input<string>;
    /**
     * Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
     */
    alertType: pulumi.Input<string>;
    /**
     * Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
     *
     * @deprecated This field is no longer needed and will be ignored
     */
    broadcastToAll?: pulumi.Input<boolean | undefined>;
    /**
     * Condition of the alert.
     */
    condition: pulumi.Input<string>;
    /**
     * Description of the alert.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the alert is disabled.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The evaluation window of the alert. By default, it is 5m0s.
     */
    evalWindow?: pulumi.Input<string | undefined>;
    /**
     * Evaluation settings for the alert (JSON). Only used when schemaVersion is v2 or higher.
     */
    evaluation?: pulumi.Input<string | undefined>;
    /**
     * The frequency of the alert. By default, it is 1m0s.
     */
    frequency?: pulumi.Input<string | undefined>;
    /**
     * Labels of the alert. Severity is a required label.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Notification settings for the alert. Only used when schemaVersion is v2 or higher.
     */
    notificationSettings?: pulumi.Input<inputs.AlertNotificationSettings | undefined>;
    /**
     * Preferred channels of the alert. By default, it is empty.
     */
    preferredChannels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Type of the alert. Possible values are: thresholdRule and promql_rule.
     */
    ruleType?: pulumi.Input<string | undefined>;
    /**
     * Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notificationSettings are supported.
     */
    schemaVersion?: pulumi.Input<string | undefined>;
    /**
     * Severity of the alert. Possible values are: info, warning, error, and critical.
     */
    severity: pulumi.Input<string>;
    /**
     * Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * Summary of the alert.
     */
    summary?: pulumi.Input<string | undefined>;
    /**
     * Version of the alert. By default, it is v4.
     */
    version?: pulumi.Input<string | undefined>;
}
