// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAlert(args: GetAlertArgs, opts?: pulumi.InvokeOptions): Promise<GetAlertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("signoz:index/getAlert:getAlert", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlert.
 */
export interface GetAlertArgs {
    id: string;
}

/**
 * A collection of values returned by getAlert.
 */
export interface GetAlertResult {
    readonly alert: string;
    readonly alertType: string;
    /**
     * @deprecated This field is no longer needed and will be ignored
     */
    readonly broadcastToAll: boolean;
    readonly condition: string;
    readonly description: string;
    readonly disabled: boolean;
    readonly evalWindow: string;
    readonly evaluation: string;
    readonly frequency: string;
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly notificationSettings: outputs.GetAlertNotificationSettings;
    readonly preferredChannels: string[];
    readonly ruleType: string;
    readonly schemaVersion: string;
    readonly severity: string;
    readonly source: string;
    readonly state: string;
    readonly summary: string;
    readonly version: string;
}
export function getAlertOutput(args: GetAlertOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAlertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("signoz:index/getAlert:getAlert", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlert.
 */
export interface GetAlertOutputArgs {
    id: pulumi.Input<string>;
}
