// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDashboard(args: GetDashboardArgs, opts?: pulumi.InvokeOptions): Promise<GetDashboardResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("signoz:index/getDashboard:getDashboard", {
        "id": args.id,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getDashboard.
 */
export interface GetDashboardArgs {
    id: string;
    version?: string;
}

/**
 * A collection of values returned by getDashboard.
 */
export interface GetDashboardResult {
    readonly collapsableRowsMigrated: boolean;
    readonly description: string;
    readonly id: string;
    readonly layout: string;
    readonly name: string;
    readonly panelMap: string;
    readonly source: string;
    readonly tags: string[];
    readonly title: string;
    readonly uploadedGrafana: boolean;
    readonly variables: string;
    readonly version: string;
    readonly widgets: string;
}
export function getDashboardOutput(args: GetDashboardOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDashboardResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("signoz:index/getDashboard:getDashboard", {
        "id": args.id,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getDashboard.
 */
export interface GetDashboardOutputArgs {
    id: pulumi.Input<string>;
    version?: pulumi.Input<string | undefined>;
}
