// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AlertArgs, AlertState } from "./alert";
export type Alert = import("./alert").Alert;
export const Alert: typeof import("./alert").Alert = null as any;
utilities.lazyLoad(exports, ["Alert"], () => require("./alert"));

export { DashboardArgs, DashboardState } from "./dashboard";
export type Dashboard = import("./dashboard").Dashboard;
export const Dashboard: typeof import("./dashboard").Dashboard = null as any;
utilities.lazyLoad(exports, ["Dashboard"], () => require("./dashboard"));

export { LogPipelineArgs, LogPipelineState } from "./logPipeline";
export type LogPipeline = import("./logPipeline").LogPipeline;
export const LogPipeline: typeof import("./logPipeline").LogPipeline = null as any;
utilities.lazyLoad(exports, ["LogPipeline"], () => require("./logPipeline"));

export { NotificationChannelArgs, NotificationChannelState } from "./notificationChannel";
export type NotificationChannel = import("./notificationChannel").NotificationChannel;
export const NotificationChannel: typeof import("./notificationChannel").NotificationChannel = null as any;
utilities.lazyLoad(exports, ["NotificationChannel"], () => require("./notificationChannel"));

export * from "./provider";
import { Provider } from "./provider";

export { SavedViewArgs, SavedViewState } from "./savedView";
export type SavedView = import("./savedView").SavedView;
export const SavedView: typeof import("./savedView").SavedView = null as any;
utilities.lazyLoad(exports, ["SavedView"], () => require("./savedView"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "signoz:index/alert:Alert":
                return new Alert(name, <any>undefined, { urn })
            case "signoz:index/dashboard:Dashboard":
                return new Dashboard(name, <any>undefined, { urn })
            case "signoz:index/logPipeline:LogPipeline":
                return new LogPipeline(name, <any>undefined, { urn })
            case "signoz:index/notificationChannel:NotificationChannel":
                return new NotificationChannel(name, <any>undefined, { urn })
            case "signoz:index/savedView:SavedView":
                return new SavedView(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("signoz", "index/alert", _module)
pulumi.runtime.registerResourceModule("signoz", "index/dashboard", _module)
pulumi.runtime.registerResourceModule("signoz", "index/logPipeline", _module)
pulumi.runtime.registerResourceModule("signoz", "index/notificationChannel", _module)
pulumi.runtime.registerResourceModule("signoz", "index/savedView", _module)
pulumi.runtime.registerResourcePackage("signoz", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:signoz") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
