// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The SigNoz log-processing pipeline set. SigNoz manages log pipelines as a single versioned, ordered collection, so this is a **singleton** resource — declare at most one. Applying publishes a new pipeline-set version; destroying publishes an empty set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as signoz from "@jooon/pulumi-signoz";
 *
 * // Singleton: declare at most one signoz_log_pipeline per SigNoz instance.
 * // Applying publishes a new pipeline-set version; destroying clears the set.
 * const main = new signoz.LogPipeline("main", {pipelines: JSON.stringify([{
 *     orderId: 1,
 *     name: "drop-health-checks",
 *     alias: "drop-health-checks",
 *     enabled: true,
 *     filter: {
 *         op: "AND",
 *         items: [{
 *             key: {
 *                 key: "http.target",
 *             },
 *             op: "=",
 *             value: "/healthz",
 *         }],
 *     },
 *     config: [],
 * }])});
 * ```
 */
export class LogPipeline extends pulumi.CustomResource {
    /**
     * Get an existing LogPipeline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LogPipelineState, opts?: pulumi.CustomResourceOptions): LogPipeline {
        return new LogPipeline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'signoz:index/logPipeline:LogPipeline';

    /**
     * Returns true if the given object is an instance of LogPipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LogPipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LogPipeline.__pulumiType;
    }

    /**
     * Ordered array of pipeline definitions as JSON. Compared semantically.
     */
    declare public readonly pipelines: pulumi.Output<string>;

    /**
     * Create a LogPipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LogPipelineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LogPipelineArgs | LogPipelineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LogPipelineState | undefined;
            resourceInputs["pipelines"] = state?.pipelines;
        } else {
            const args = argsOrState as LogPipelineArgs | undefined;
            if (args?.pipelines === undefined && !opts.urn) {
                throw new Error("Missing required property 'pipelines'");
            }
            resourceInputs["pipelines"] = args?.pipelines;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LogPipeline.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LogPipeline resources.
 */
export interface LogPipelineState {
    /**
     * Ordered array of pipeline definitions as JSON. Compared semantically.
     */
    pipelines?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a LogPipeline resource.
 */
export interface LogPipelineArgs {
    /**
     * Ordered array of pipeline definitions as JSON. Compared semantically.
     */
    pipelines: pulumi.Input<string>;
}
