// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A SigNoz notification channel (Slack, webhook, PagerDuty, email, OpsGenie, MS Teams). **Write operations require an admin Service Account token.** The receiver config goes in `data` as JSON.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as signoz from "@jooon/pulumi-signoz";
 *
 * // Notification channels require an ADMIN SigNoz service-account token.
 * const slack = new signoz.NotificationChannel("slack", {
 *     name: "team-alerts",
 *     data: JSON.stringify({
 *         slack_configs: [{
 *             send_resolved: true,
 *             api_url: "https://hooks.slack.com/services/T000/B000/XXXX",
 *             channel: "#alerts",
 *         }],
 *     }),
 * });
 * ```
 */
export class NotificationChannel extends pulumi.CustomResource {
    /**
     * Get an existing NotificationChannel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NotificationChannelState, opts?: pulumi.CustomResourceOptions): NotificationChannel {
        return new NotificationChannel(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'signoz:index/notificationChannel:NotificationChannel';

    /**
     * Returns true if the given object is an instance of NotificationChannel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationChannel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationChannel.__pulumiType;
    }

    /**
     * Receiver configuration as JSON, e.g. `{"slackConfigs":[{"apiUrl":"…","channel":"#alerts"}]}`. Compared semantically.
     */
    declare public readonly data: pulumi.Output<string>;
    /**
     * Unique channel name.
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a NotificationChannel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NotificationChannelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NotificationChannelArgs | NotificationChannelState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NotificationChannelState | undefined;
            resourceInputs["data"] = state?.data;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as NotificationChannelArgs | undefined;
            if (args?.data === undefined && !opts.urn) {
                throw new Error("Missing required property 'data'");
            }
            resourceInputs["data"] = args?.data;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NotificationChannel.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NotificationChannel resources.
 */
export interface NotificationChannelState {
    /**
     * Receiver configuration as JSON, e.g. `{"slackConfigs":[{"apiUrl":"…","channel":"#alerts"}]}`. Compared semantically.
     */
    data?: pulumi.Input<string | undefined>;
    /**
     * Unique channel name.
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a NotificationChannel resource.
 */
export interface NotificationChannelArgs {
    /**
     * Receiver configuration as JSON, e.g. `{"slackConfigs":[{"apiUrl":"…","channel":"#alerts"}]}`. Compared semantically.
     */
    data: pulumi.Input<string>;
    /**
     * Unique channel name.
     */
    name?: pulumi.Input<string | undefined>;
}
