// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A saved SigNoz explorer view (logs or traces). The query state goes in `data` as JSON.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as signoz from "@jooon/pulumi-signoz";
 *
 * const errors = new signoz.SavedView("errors", {
 *     name: "Errors (last 15m)",
 *     sourcePage: "logs",
 *     data: JSON.stringify({
 *         compositeQuery: {
 *             queryType: "builder",
 *             panelType: "list",
 *             builderQueries: {
 *                 A: {
 *                     dataSource: "logs",
 *                     queryName: "A",
 *                     aggregateOperator: "noop",
 *                     expression: "A",
 *                     disabled: false,
 *                 },
 *             },
 *         },
 *     }),
 * });
 * ```
 */
export class SavedView extends pulumi.CustomResource {
    /**
     * Get an existing SavedView resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SavedViewState, opts?: pulumi.CustomResourceOptions): SavedView {
        return new SavedView(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'signoz:index/savedView:SavedView';

    /**
     * Returns true if the given object is an instance of SavedView.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SavedView {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SavedView.__pulumiType;
    }

    /**
     * Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
     */
    declare public readonly data: pulumi.Output<string>;
    /**
     * View name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Explorer the view belongs to: `logs` or `traces`.
     */
    declare public readonly sourcePage: pulumi.Output<string>;

    /**
     * Create a SavedView resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SavedViewArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SavedViewArgs | SavedViewState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SavedViewState | undefined;
            resourceInputs["data"] = state?.data;
            resourceInputs["name"] = state?.name;
            resourceInputs["sourcePage"] = state?.sourcePage;
        } else {
            const args = argsOrState as SavedViewArgs | undefined;
            if (args?.data === undefined && !opts.urn) {
                throw new Error("Missing required property 'data'");
            }
            if (args?.sourcePage === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourcePage'");
            }
            resourceInputs["data"] = args?.data;
            resourceInputs["name"] = args?.name;
            resourceInputs["sourcePage"] = args?.sourcePage;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SavedView.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SavedView resources.
 */
export interface SavedViewState {
    /**
     * Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
     */
    data?: pulumi.Input<string | undefined>;
    /**
     * View name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Explorer the view belongs to: `logs` or `traces`.
     */
    sourcePage?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SavedView resource.
 */
export interface SavedViewArgs {
    /**
     * Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
     */
    data: pulumi.Input<string>;
    /**
     * View name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Explorer the view belongs to: `logs` or `traces`.
     */
    sourcePage: pulumi.Input<string>;
}
